--------------------------------------------------------
--  파일이 생성됨 - 화요일-3월-05-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table FOOD_TBL
--------------------------------------------------------

  CREATE TABLE "FOOD"."FOOD_TBL" 
   (	"ID" NUMBER(19,0), 
	"COOKING_INSTRUCTION" VARCHAR2(1000 CHAR), 
	"INGREDIENT" VARCHAR2(1000 CHAR), 
	"MINOR_INGREDIENT" VARCHAR2(1000 CHAR), 
	"REFERENCE" VARCHAR2(1000 CHAR), 
	"COOK" VARCHAR2(255 CHAR), 
	"COOKING_ORIGIN" VARCHAR2(255 CHAR), 
	"FOOD_IMG" VARCHAR2(255 CHAR), 
	"FOOD_NAME" VARCHAR2(255 CHAR), 
	"FOOD_TYPE" VARCHAR2(255 CHAR), 
	"INFORMATION_PROVIDER" VARCHAR2(255 CHAR), 
	"RECIPE" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into FOOD.FOOD_TBL
SET DEFINE OFF;
Insert into FOOD.FOOD_TBL (ID,COOKING_INSTRUCTION,INGREDIENT,MINOR_INGREDIENT,REFERENCE,COOK,COOKING_ORIGIN,FOOD_IMG,FOOD_NAME,FOOD_TYPE,INFORMATION_PROVIDER,RECIPE) values (98,'1. 떫은 감을 따서 껍질과 씨를 제거한 후 솥에 넣고 감이 살짝 잠길 정도의 물을 부어 약한 불로 잘 저어 주면서 3일 정도 조린다. 2. 감의 부피가 1/3 정도가 되도록 조려지면 고운체에 걸러 낸다. 3. 2에 감즙에 1.2배 분량의 찹쌀가루를 솔솔 뿌리면서 약한 불에서 조린다. 4. 찹쌀가루가 잘 익으면 죽처럼 기포가 올라온다. 이때 불을 약하게 줄이고 솥뚜껑을 살짝 열어 수증기를 증발 시킨다. 5. 20분 정도 후 항아리에 담아 식히고 넓은 쟁반에 고명을 뿌린 후 밤 크기 정도로 떼어 준비한 고명을 묻힌다.','떫은 감 1kg, 물 1L(5컵), 찹쌀가루 적량','<고명> 콩가루, 석이버섯채, 감채, 밤채 적량','해남 윤씨(고산 윤선도) 종가에서 내려오는 전통음식이다. 떡을 항아리에 담아 보관해야 색과 맛이 그대로 유지된다고 한다.','김은수(해남 윤씨 종부), 전라남도 해남군 연동',null,'blank_image.png','감단자','떡류 > 떡류',null,'가열하여 익히는 음식 > 물을 이용한 음식 > 끓이는 음식');
Insert into FOOD.FOOD_TBL (ID,COOKING_INSTRUCTION,INGREDIENT,MINOR_INGREDIENT,REFERENCE,COOK,COOKING_ORIGIN,FOOD_IMG,FOOD_NAME,FOOD_TYPE,INFORMATION_PROVIDER,RECIPE) values (99,'1. 중간 정도의 배추로 잎이 얇은 것을 골라 뿌리 쪽을 갈라 씻어 소금물에 절였다가 물기를 짠 후 3cm 길이로 썰어 놓는다. 2. 무와 배는 껍질을 벗겨 2.5×3×0.3cm의 두께로 굵게 채 썰고 잣은 고깔을 떼어 놓는다. 3. 오이는 무와 같은 크기로 썰고, 밤은 껍질을 벗겨 0.3cm 두께로 굵게 채썰고, 잣은 고깔을 떼어 놓는다. 4. 실파와 미나리는 다듬어 씻어서 3cm 길이로 썬다. 5. 생굴은 소금물에 조심해서 씻어 건지고, 낙지와 전복은 소금으로 문질러 씻어 낙지는 3cm 길이로 썰고 전복은 같은 길이로 얇게 저민다. 6. 북어는 물에 불려서 껍질을 벗겨 2cm 길이로 토막 낸다. 7. 배추와 무 절인 국물에 고춧가루를 넣어 불려서 물을 곱게 들인 후 절인 배추와 무, 오이, 미나리, 실파, 낙지, 전복, 복어를 넣고 고루 섞은 다음 감동젓(곤쟁이젓)과 다진 마늘, 다진 생강을 넣어 고루 버무린 후 2큰술의 소금으로 간을 맞춘다. 8. 마지막에 생굴, 실고추, 밤채, 잣을 넣고 살살 버무려서 항아리에 꼭꼭 눌러 담고 배추 우거지로 덮어서 익힌다.','무 850(1개), 배 700g(2개), 오이 300g(2개), 실파 100g, 미나리 100g, 밤 100g(7개), 생굴 200g(1컵), 낙지 200g(1마리), 전복 200g(2마리), 잣 2큰술, 실고추 2g, 배추 1kg(1포기), 북어 140g(1마리), 설탕 2큰술, 소금(호렴) 1/2컵, 물 적량','<양념> 다진마늘, 다진 생강 약간, 고춧가루 1컵, 감동젓(곤쟁이젓) 2컵, 설탕 2큰술 소금 2큰술,','자하젓, 곤쟁이젓 이라고도 하는 감동젓은 서해안에서만 서식하는 작은 자색의 새우로 담그며 보리새우와 비슷하나 크기가 매우 작다. 서울이나 경기 지방에서는 감동젓무라 하여 깍두기도 담그고, 찌개의 간을 맞추기도 하는 등 귀하게 썼다.',null,'전희정·이효지·한영실, 한국전통음식, 문화관광부, 2000','80736ff7-e54d-4288-8da9-f850c726cc26.jpg','감동젓무김치','부식류 > 김치류 > 김치류 > 무류',null,'가열하지 않는 음식 > 소금이나 장류에 절이는 음식 > 소금이나 장류에 절이는 음식');
Insert into FOOD.FOOD_TBL (ID,COOKING_INSTRUCTION,INGREDIENT,MINOR_INGREDIENT,REFERENCE,COOK,COOKING_ORIGIN,FOOD_IMG,FOOD_NAME,FOOD_TYPE,INFORMATION_PROVIDER,RECIPE) values (100,'1. 쇠고기는 0.3cm로 납작하게 썰어서 고기 양념으로 무치고, 배추는 5cm넓이와 너비4cm길이로 썰며, 쪽파는 5cm로 자른다. 2. 두부는 2.5×3.5×0.5cm 크기로 납작하게 썰고, 건표고버섯은 불려서 기둥을 뗀 다음 0.3cm로 굵게 채 썬다. 3. 쑥갓을 씻어서 5cm 길이로 자른다. 4. 고기, 배추, 표고버섯을 순서대로 넣고 볶다가 물을 붓고 감동젓으로 간을 하고 두부와 어슷썬 대파를 넣고 나중에 쑥갓을 넣는다.','쇠고기 100g, 배추 100g, 두부 300g(1/2모), 쪽파 3뿌리, 쑥갓 50g, 물 600mL(3컵), 건표고버섯 10g(3개), 대파 약간, 감동젓 4큰술','<고기 양념> 소금 1작은술, 후춧가루 1/4작은술','감동젓은 푹 삭힌 곤쟁이젓으로, 곤쟁이(紫蝦)는 인천(통인)의 산출식품으로『도문대작』에 기록되어 있다. 감동젓은 18세기 초기『춘향가』에도 등장하는데, 노론, 소론의 사색당파가 요란했던 시절에 유독 노론을 주창하는 사대부 집에서 이 음식을 만들어 먹었으며 구한말 갑신정변으로 희생된 김병학 대감의 손부(孫婦)인 한영수 할머니가 만들었다고 한다. 젓갈을 오래 삭힌 것을 음식에 사용하여 맛을 내는 방법은 이미 중국의 주나라 때에 유래되어 우리의 젓찌개로 발전되어 왔다고 보며, 생선이나 갑각류의 젓갈을 푹 삭힘으로써 비린 맛은 없어지고 유리 아미노산의 맛성분만으로 감칠맛을 낸다. 이것이 겨울을 나면서 곰삭아 건더기가 없을 정도가 된 것이 감동이며, 이 젓으로 간을 맞추어 끓인 맑은 찌개가 감동젓찌개이다.',null,'문화공보부 문화재관리국, 한국민속종합조사보고서(향토음식편), 1984','fbfc0282-d052-4871-b0ab-a2bd7225c23f.jpg','감동젓찌개(곤쟁이젓찌개)','부식류 > 구이류 > 구이류 > 육류',null,'가열하여 익히는 음식 > 물을 이용한 음식 > 끓이는 음식');
Insert into FOOD.FOOD_TBL (ID,COOKING_INSTRUCTION,INGREDIENT,MINOR_INGREDIENT,REFERENCE,COOK,COOKING_ORIGIN,FOOD_IMG,FOOD_NAME,FOOD_TYPE,INFORMATION_PROVIDER,RECIPE) values (19,'1. 가자미는 내장을 빼고 깨끗하게 씻어 3×3cm 길이로 토막 내어 엿기름가루에 재운다. 2. 조는 깨끗하게 씻어 고슬고슬하게 밥을 지어 식힌다. 3. 무는 나박썰기(2×2×0.3cm) 하여 소금에 절여 물기를 뺀다. 4. 준비된 모든 재료를 식해 양념으로 버무린 후 항아리에 꼭꼭 눌러 담아 7일 정도 숙성시킨다.','가자미 350g(1마리), 무 150g, 조 220g(1 1/2컵), 엿기름가루 100g(1컵), 소금 1작은술, 물 200mL(1컵)','[식해 양념] 고춧가루 1컵, 다진 마늘 1큰술, 다진 생강 1작은술, 소금 3큰술','산간지방에 생선이 귀하고 운반하기 힘들고 보관하기 어려울 때 먹었다고 한다.',null,'문화공보부 문화재관리국, 한국민속종합조사보고서(경상남도 편), 1972','blank_image.png','가자미식해','부식류 > 젓갈 및 식해류 > 식해 > 식해',null,'가열하지 않는 음식 > 소금이나 장류에 절이는 음식 > 소금이나 장류에 절이는 음식');
Insert into FOOD.FOOD_TBL (ID,COOKING_INSTRUCTION,INGREDIENT,MINOR_INGREDIENT,REFERENCE,COOK,COOKING_ORIGIN,FOOD_IMG,FOOD_NAME,FOOD_TYPE,INFORMATION_PROVIDER,RECIPE) values (20,'1. 가자미는 깨끗하게 손질하여 3cm 크기로 썰어 엿기름가루를 섞어 재운다. 2. 조는 씻어 고슬고슬하게 쪄서 식혀 놓는다. 3. 무는 채 썰어(5×0.2×0.2cm) 소금에 절여서 물기를 꼭 짠다. 4. 준비된 모든 재료에 양념을 넣고 골고루 버무려 항아리에 꼭꼭 눌러 담아 7일 정도 삭힌다.','가자미 340g(1마리), 무 1.5kg(1 1/2개), 조 300g(2컵), 엿기름가루 50g(1/2컵), 소금 1큰술','[양념] 고춧가루 2컵, 다진 마늘 3큰술, 다진 생강 1큰술, 소금 3큰술, 검은깨 1큰술',null,'최용선, 경상북도 울진군 기성면 봉산 2리','문화공보부 문화재관리국, 한국민속종합조사보고서(향토음식편), 1984 윤숙경 박미남, 경상북도 동해안 지역 식생활문화에 관한연구(1), 한국식생활문화학회지, 14(2), 1999 농촌진흥청, 향토음식 : www2.rda.go.kr/food/, 2006','a1583fd4-9cb4-46cd-96a9-edb1d9d4af23.jpg','가자미식해','부식류 > 젓갈 및 식해류 > 식해 > 식해','신복순, 경상북도 안동시 정상동 우복순, 경상북도 달성군 화원읍 본리리','가열하지 않는 음식 > 소금이나 장류에 절이는 음식 > 소금이나 장류에 절이는 음식');
Insert into FOOD.FOOD_TBL (ID,COOKING_INSTRUCTION,INGREDIENT,MINOR_INGREDIENT,REFERENCE,COOK,COOKING_ORIGIN,FOOD_IMG,FOOD_NAME,FOOD_TYPE,INFORMATION_PROVIDER,RECIPE) values (21,'1. 가자미는 작은 것으로 납작하게 썰어서 소금에 절여 하룻밤 두었다가 면포에 싸서 무거운 것으로 눌러 물기를 뺀다. 눌러 두면 고기가 꼬들꼬들해진다. 2. 쌀로 고슬고슬하게 밥을 지어서 차게 식힌 다음 다진 파, 다진 마늘, 다진 생강, 고춧가루, 소금을 섞어 버무린다. 3. 무는 나박썰어(2.5×2.5×0.3cm) 소금에 절인다. 4. 가자미를 엿기름가루에 버무리고 양념한 밥과 골고루 섞는다. 5. 항아리에 꼭꼭 눌러 담고 무거운 돌로 꼭 눌러 두고 삭힌다. 겨울철에는 1주일 정도 삭힌다.','가자미 4kg(10마리), 무 150g, 엿기름가루 50g(1/2컵), 쌀 180g(1컵), 다진 파 4큰술, 다진 마늘 4큰술, 다진 생강 2큰술, 고춧가루 1/2컵, 밥 짓는 물 200mL(1컵), 소금 약간',null,null,null,null,'blank_image.png','가자미식해','부식류 > 젓갈 및 식해류 > 식해 > 식해',null,'가열하지 않는 음식 > 소금이나 장류에 절이는 음식 > 소금이나 장류에 절이는 음식');
Insert into FOOD.FOOD_TBL (ID,COOKING_INSTRUCTION,INGREDIENT,MINOR_INGREDIENT,REFERENCE,COOK,COOKING_ORIGIN,FOOD_IMG,FOOD_NAME,FOOD_TYPE,INFORMATION_PROVIDER,RECIPE) values (22,'1. 가자미는 손바닥만한 노란색의 참가자미로 싱싱한 것을 골라서 내장을 빼고 비늘을 말끔히 긁어서 소금을 고루 뿌려 절인 후 채반에 널어 꾸덕꾸덕하게 말린다. 2. 말린 가자미는 폭 3㎝로 토막낸다. 3. 메조는 일어 씻어 밥을 되게 짓는다. 4. 엿기름가루를 물에 주물러 가라앉혀서 고운체에 엿기름물을 거른 다음 냄비에 부어 끓여 식힌다. 5. 무는 굵게 채 썰어서(5×0.3×0.3cm) 소금에 절여 물기를 짠다. 6. 큰 그릇에 조밥을 담아 고춧가루로 고루 버무린 다음 가자미와 절인 무를 합하여 양념을 넣고 고루 버무려서 항아리에 꼭꼭 눌러 담아 돌이나 접시로 눌러서 삭힌다. 7. 덥지 않은 곳에 두면 일주일이면 물이 생기면서 숙성된다.','가자미 4kg(10마리), 소금 1/2컵, 조 150g(1컵), 엿기름가루 120g(1컵), 무 400g(1/2개), 고춧가루 1컵, 밥 짓는 물 200mL(1컵), 물 600mL(3컵)','[양념] 다진파 4큰술, 다진 마늘 2큰술, 다진 생강 1큰술, 소금 1컵, 고운 고춧가루 5큰술, 마늘채 2큰술, 생강채 1/2큰술','식해는 내장을 제거한 생선에 쌀밥 또는 조밥과 채소를 넣어 젖산 발효시킨 식품이다. 오늘날의 생선식해는 함경도 지방의 향토음식으로 알려져 있으나 1600년 임진왜란 중 쓰여진 오희문의『쇄미록』에 보면 여러 가지 생선식해가 서울의 양반가에서도 상용되었던 것을 알 수 있다. 우리나라의 강원도와 같은 해안 지방에서 겨울철 단백질과 칼슘을 보충하기 위해 생선을 이용한 저장발효식품으로 입맛을 돋우며, 장기간 보관해 가며 먹을 수 있는 식해의 형태로 음식을 만들어 먹었다.',null,null,'blank_image.png','가자미식해','부식류 > 젓갈 및 식해류 > 식해 > 식해',null,'가열하지 않는 음식 > 소금이나 장류에 절이는 음식 > 소금이나 장류에 절이는 음식');
Insert into FOOD.FOOD_TBL (ID,COOKING_INSTRUCTION,INGREDIENT,MINOR_INGREDIENT,REFERENCE,COOK,COOKING_ORIGIN,FOOD_IMG,FOOD_NAME,FOOD_TYPE,INFORMATION_PROVIDER,RECIPE) values (23,'1. 가자미는 싱싱한 것으로 골라 비늘을 긁고 내장을 뺀 다음 통째로 소금을 뿌려 냉장고나 서늘한 곳에 하루쯤 둔다. 2. 실고추는 짧게 끓어서 양념을 넣고 고루 섞는다. 3. 절인 가자미를 5-6cm길이로 두세 토막 내어 석쇠에 얹어 그대로 살짝 구운 후 위의 양념을 바르면서 앞뒤를 고루 굽는다.','소금 1큰술, 가자미 1kg(4마리)','<양념 간장> 간장 3큰술, 다진 파 1큰술, 다진 생강 1작은술, 고춧가루 2작은술, 참기름 2작은술, 깨소금 2작은술, 실고추 약간',null,null,'전희정·이효지·한영실, 한국전통음식, 문화관광부, 2000','blank_image.png','가자미양념구이','부식류 > 구이류 > 구이류 > 어패류',null,'가열하여 익히는 음식 > 굽는 음식 > 굽는 음식');
Insert into FOOD.FOOD_TBL (ID,COOKING_INSTRUCTION,INGREDIENT,MINOR_INGREDIENT,REFERENCE,COOK,COOKING_ORIGIN,FOOD_IMG,FOOD_NAME,FOOD_TYPE,INFORMATION_PROVIDER,RECIPE) values (13,'1. 가오리는 내장을 제거한 후 씻어서 얇게 저며 썬다. 2. 1에 막걸리를 넣고 세게 주물러 미끈미끈한 것을 제거한 다음 깨끗한 물로 씻어서 마른 면포로 물기를 제거해 둔다. 3. 오이는 반달썰기 하여(0.3cm) 소금에 절여 물기를 짜고, 미나리는 5cm 길이로 썬다. 4. 무는 채 썰고(5×0.3×0.3cm), 붉은 고추는 어슷하게 썬다.(0.3cm). 5. 오이와 무는 고춧가루로 먼저 붉은색을 들이고 가오리와 나머지 초고추장 양념 재료를 넣어 버무린 후 소금으로 간을 맞추고 미나리와 붉은고추를 넣어 무친다.','가오리 1마리, 오이 145g(1개), 미나리 100g, 무 50g, 붉은 고추 15g(1개), 막걸리 약간, 소금 약간','[초고추장 양념] 고추장 3큰술, 식초 3큰술, 설탕 3큰술, 고춧가루 2큰술, 다진 파 2큰술, 다진 마늘 1큰술, 다진 생강 1작은술, 깨소금 2큰술, 소금 약간',null,null,'여수시농업기술센터, 관광 여수의 맛 자랑, 2001 완도군농업기술센터, 세계로! 미래로! 청해진 음식기행 100선, 2001 광주광역시 북구, 향토음식 박물관 건립방안 연구, 2003','2f6bc8ff-55e7-46af-b2d4-30627c3df79d.jpg','가오리회','부식류 > 회류 > 생회 > 어패류',null,'가열하지 않는 음식 > 날것에 조미료를 곁들여 먹는 음식 > 날것에 조미료를 곁들여 먹는 음식');
Insert into FOOD.FOOD_TBL (ID,COOKING_INSTRUCTION,INGREDIENT,MINOR_INGREDIENT,REFERENCE,COOK,COOKING_ORIGIN,FOOD_IMG,FOOD_NAME,FOOD_TYPE,INFORMATION_PROVIDER,RECIPE) values (14,'1. 가오리는 내장을 제거한 후 씻어서 얇게 저며 썬 다음 막걸리를 넣고 주물러 점액질을 제거하고 깨끗한 물로 씻어서 마른 면포로 닦아 물기를 제거해 둔다. 2. 무는 가늘게 채 썰고(5×0.2×0.2cm), 오이는 반달썰기 하여(0.4~0.5cm) 소금에 절여 물기를 짜 둔다. 3. 미나리는 5㎝ 길이로 썰고, 붉은 고추는 어슷썬다. 4. 무와 오이는 고춧가루로 먼저 색을 들이고 가오리에 나머지 양념을 넣어 버무린 후 미나리를 넣고 무친다.','가오리 1마리, 미나리 100g, 무 50g, 오이 140g(1개), 붉은 고추 15g(1개), 막걸리 200mL(1컵), 소금 약간','[양념장] 고추장 2큰술, 고춧가루 2큰술, 다진 파 2큰술, 다진 마늘 1큰술, 다진 생강 1작은술, 설탕 3큰술, 깨소금 2큰술','홍어는 값이 비싸서 가오리를 대용으로 회를 떠서 먹었는데, 크기가 작을수록 뼈가 연하다. 가오리회는 보통 경조사에 많이 쓰인다.',null,null,'bed7c94f-1458-4df4-9ed9-2bc4e40b8292.jpg','가오리회','부식류 > 회류 > 생회 > 어패류',null,'가열하지 않는 음식 > 날것에 조미료를 곁들여 먹는 음식 > 날것에 조미료를 곁들여 먹는 음식');
Insert into FOOD.FOOD_TBL (ID,COOKING_INSTRUCTION,INGREDIENT,MINOR_INGREDIENT,REFERENCE,COOK,COOKING_ORIGIN,FOOD_IMG,FOOD_NAME,FOOD_TYPE,INFORMATION_PROVIDER,RECIPE) values (15,'1. 가자미는 지느러미와 내장을 제거하고 깨끗이 씻어 2토막을 낸다. 2. 두부는 3×4×1cm 크기로 잘라 소금 간을 하고 달군 팬에 식용유를 두르고 노릇하게 지진다. 3. 양파는 0.5cm 너비로 썰고, 풋고추, 붉은 고추는 어슷썬다(0.3cm). 4. 냄비에 가자미를 넣고 지진 두부를 위에 얹은 다음 양념을 넣고 물을 자작하게 부어 끓인다. 5. 4가 끓으면 양파, 풋고추, 붉은 고추, 대파를 넣고 소금으로 간을 하여 국물을 끼얹어 가면서 한소끔 더 끓인다.','가자미(납세미) 340g(1마리), 두부 250g(1/2모), 양파 100g(2/3개), 풋고추 15g(1개), 붉은 고추 15g(1개), 대파 10g(1/4뿌리), 물 400mL(2컵), 식용유 1작은술, 소금 약간','[양념] 고춧가루 2큰술, 고추장 1큰술, 마늘 10g(2쪽), 생강 5g(1쪽), 설탕, 소금, 후춧가루 약간',null,'정계임, 경상남도 진주시 대안동',null,'32c90283-70e3-4c73-b634-dc295780b91d.jpg','가자미두부찌개(납세미두부찌개)','부식류 > 전골 및 찌개류 > 찌개 > 어패류',null,'가열하여 익히는 음식 > 물을 이용한 음식 > 끓이는 음식');
Insert into FOOD.FOOD_TBL (ID,COOKING_INSTRUCTION,INGREDIENT,MINOR_INGREDIENT,REFERENCE,COOK,COOKING_ORIGIN,FOOD_IMG,FOOD_NAME,FOOD_TYPE,INFORMATION_PROVIDER,RECIPE) values (16,'1. 가자미를 굵은 소금으로 치대어 씻는다. 2. 가자미의 머리, 지느러미, 내장을 제거하고 깨끗이 씻어 뼈째로 어슷썬다(0.3cm). 3. 생미역은 소금으로 문질러 깨끗이 씻어 4~5cm 길이로 썰고, 양파, 깻잎은 0.5cm 너비로 채 썬다. 4. 실파는 다듬어 3~4cm 길이로 썰고, 풋고추와 붉은고추는 어슷썰기 한다(0.3cm). 5. 준비된 모든 재료에 초고추장과 참기름을 넣어 무친다.','가자미 340g(1마리), 양파 70g(1/2개), 생미역 30g, 실파 20g, 풋고추 30g(2개), 붉은 고추 30g(2개), 깻잎 10g(6장), 참기름 1작은술, 굵은 소금 1큰술','[초고추장] 고추장 2큰술, 식초 2큰술, 다진 마늘 2큰술, 설탕 1작은술, 통깨 1작은술',null,'김필화, 경상북도 포항시',null,'e7b24878-b195-47a2-8582-17064a36c7f7.jpg','가자미무침회','부식류 > 회류 > 무침 > 어패류',null,'가열하지 않는 음식 > 날것에 조미료를 곁들여 먹는 음식 > 날것에 조미료를 곁들여 먹는 음식');
Insert into FOOD.FOOD_TBL (ID,COOKING_INSTRUCTION,INGREDIENT,MINOR_INGREDIENT,REFERENCE,COOK,COOKING_ORIGIN,FOOD_IMG,FOOD_NAME,FOOD_TYPE,INFORMATION_PROVIDER,RECIPE) values (17,'1. 마른 미역은 따뜻한 물에 불린 후 주물러 씻어 건져 물기를 뺀 다음 4~5cm 길이로 썬다. 2. 가자미는 내장, 비늘을 제거하고 깨끗이 씻어 3~4토막 낸다. 3. 냄비에 참기름을 두르고 불린 미역을 볶는다. 4. 3에 물을 붓고 국간장으로 간을 한 후 가자미를 넣어 끓인다.','가자미 350g(대 1마리), 마른 미역 30g, 물 1.4L(7컵), 국간장 1 1/3큰술, 참기름 1작은술',null,'가자미 대신 광어나 대구를 쓰기도 하며 국물에 들깻가루를 같이 넣기도 한다.','김옥환, 경상북도 영천시 도동','영천시농업기술센터, 향토음식 맥잇기 고향의 맛, 2001','ed65c7eb-2489-460b-b36d-107a4ed79185.jpg','가자미미역국','부식류 > 국 및 탕류 > 맑은국 > 해조류','김명순, 경상북도 경주시 감손1리','가열하여 익히는 음식 > 물을 이용한 음식 > 끓이는 음식');
Insert into FOOD.FOOD_TBL (ID,COOKING_INSTRUCTION,INGREDIENT,MINOR_INGREDIENT,REFERENCE,COOK,COOKING_ORIGIN,FOOD_IMG,FOOD_NAME,FOOD_TYPE,INFORMATION_PROVIDER,RECIPE) values (18,'1. 마른 미역을 물에 불려서 씻어 5~6cm 길이로 자른다. 2. 가자미는 비늘과 내장을 제거하고 씻은 후 5~6cm 크기로 토막 낸다. 3. 냄비에 참기름을 두르고 1을 볶다가 물을 붓는다. 4. 3이 끓으면 2의 가자미를 넣어 은근한 불에서 끓인 후 국간장으로 간을 한다.','가자미 2마리,마른 미역 30g,물 1.4L(7컵),국간장 1 1/2큰술,참기름 약간',null,'·가자미 대신 흰살생선(도다리, 광어, 양태 등)을 넣기도 한다. ·가자미는 손질하여 삶아 살을 발라 내어 국물과 함께 이용하기도 한다.',null,'거제시농업기술센터, 거제향토음식, 1998 울산광역시농업기술센터, 울산향토음식, 2001','blank_image.png','가자미미역국','부식류 > 국 및 탕류 > 맑은국 > 해조류',null,'가열하여 익히는 음식 > 물을 이용한 음식 > 끓이는 음식');
Insert into FOOD.FOOD_TBL (ID,COOKING_INSTRUCTION,INGREDIENT,MINOR_INGREDIENT,REFERENCE,COOK,COOKING_ORIGIN,FOOD_IMG,FOOD_NAME,FOOD_TYPE,INFORMATION_PROVIDER,RECIPE) values (7,'1. 바다에서 채취한 가시리를 바닷물에 깨끗이 헹군 후 3일간 자연건조시킨다. 2. 1을 깨끗이 다듬은 후 절구에 빻아 굵은 체에 내린다. 3. 체에 내린 가시리를 물에 3번 정도 헹궈 체에 건져 놓는다. 4. 솥에 3의 재료의 2배 정도 물을 붓고 4시간 정도 졸이다가 죽처럼 걸쭉해지면 불을 끈 뒤 30분 정도 뜸을 들인다. 5. 4에 소금으로 간을 맞춘 뒤 성형 틀에 부어 9시간 정도 굳힌다.','가시리 1kg, 소금 1 2/3큰술, 물 1.5L(7 1/2컵)',null,'·강원도 고성군 현내면 마차진리 사람들은 겨울철이면 ''''가시리 묵''''을 만들어 먹는다. 짭짤한 갯 내음이 물씬거리는 가시리 묵은 이 지방에서 예로부터 내려오는 토속 전통음식이다. 가시리는 10월부터 이듬해 1월 사이 강원도 고성의 바닷물이 찰랑찰랑하는 갯바위에 거뭇거뭇 붙어 자라는 해조류다. 옛날 먹을 것이 없을 때 이 가시리를 긁어 모아 말렸다가 묵을 만들어 먹었다. ·보통 마른 가시리 2kg으로 묵 130모를 만든다. 가시리는 겨울음식으로 여름에는 잘 굳지 않고, 겨울에도 기온이 영하권으로 내려가야 쫀득한 제 맛을 낸다.','이복덕, 강원도 고성군 현내면 마차진리',null,'3ae511fd-2bd8-4b98-936f-fa74d917c05e.jpg','가시리묵','부식류 > 묵 및 두부류 > 묵 > 묵',null,'가열하여 익히는 음식 > 물을 이용한 음식 > 약간의 수분을 양념과함께 넣고 익혀 양념이 식품에 스며들게 하는 음식');
Insert into FOOD.FOOD_TBL (ID,COOKING_INSTRUCTION,INGREDIENT,MINOR_INGREDIENT,REFERENCE,COOK,COOKING_ORIGIN,FOOD_IMG,FOOD_NAME,FOOD_TYPE,INFORMATION_PROVIDER,RECIPE) values (8,'[밑술 만들기] 1. 찹쌀을 씻어서 12~15시간 정도 물에 담가 불린 다음 깨끗이 씻어서 소쿠리에 담아 물기를 뺀다. 2. 불린 쌀을 시루에 담아 불을 때고, 가마솥에서 김이 난 지 15분 정도 지나 뜸이 들면 불을 끈다. 3. 고두밥에 멍석 위에 널어 한 김 나간 후 누룩을 섞어 놓는다. 4. 술독을 깨끗이 세척한 후 독 안에 불을 피워 소독한다. 5. 3을 술독에 넣고 엿기름가루와 물 10L를 부어 잘 혼합한 다음 그늘에서 3~4일간 발효시켜 밑술을 만든다. [덧술 만들기] 6. 찹쌀을 씻어서 12~15시간 정도 물에 담가 불린 다음 깨끗이 씻어서 소쿠리에 담아 물기를 뺀다. 7. 찹쌀을 시루에 담아 불을 때고, 가마솥에서 김이 난 지 15분 정도 지나 뜸이 들면 불을 끈다. 8. 고두밥을 멍석에 널어 한 김 나간 후 누룩을 섞어서 다시 멍석에 널어 완전히 식힌다. 9. 8에 밑술과 물을 술독에 붓는다. 10. 말린 야생국화, 구기자, 참솔잎을 곱게 빻아서 술독에 넣어 고루 섞는다. 11. 참나무숯(이물질을 없앰)과 마른 고추 3~4개를 띄운 다음 한지로 술독을 싸고 뚜껑을 덮어 밀봉한다. 15. 그늘(저온)에서 100일간 저장한다.','찹쌀 90kg, 누룩 230g, 말린 야생국화 100g, 구기자 100g, 참솔잎(5-6월 경에 채취한 것) 100g, 참나무 숯 약간, 마른 고추 4개, 물 150L','[밑술(주모) 재료] 찹쌀 7kg, 누룩 180g, 엿기름 30g, 물 10L',null,null,null,'blank_image.png','가야곡왕주','발효식품류 > 주류 > 약주 및 탁주류 > 약주 및 탁주류',null,'가열하여 익히는 음식 > 물을 이용한 음식 > 수증기로 찌는 음식');
Insert into FOOD.FOOD_TBL (ID,COOKING_INSTRUCTION,INGREDIENT,MINOR_INGREDIENT,REFERENCE,COOK,COOKING_ORIGIN,FOOD_IMG,FOOD_NAME,FOOD_TYPE,INFORMATION_PROVIDER,RECIPE) values (9,'1. 가오리는 껍질과 내장을 제거하고 깨끗이 씻는다. 2. 방아잎은 듬성듬성 다지고, 풋고추, 붉은 고추는 반을 갈라 씨를 빼고 다진다. 3. 준비된 방아잎, 풋고추, 붉은 고추에 양념장을 넣고 잘 섞는다. 4. 김이 오른 찜통에 면포를 깔고 가오리를 올린 후 3의 양념을 발라 20분 정도 찐다. 5. 실고추와 통깨를 올린다.','가오리 500g, 방아잎 300g, 풋고추 15g(1개), 붉은고추 15g(1개), 통깨 1/2큰술, 실고추 약간','[양념장] 된장 2큰술, 다진 파 1큰술, 다진 마늘 1/2큰술',null,'정계임, 경상남도 진주시 대안동',null,'f8665503-a291-45ab-b66a-d4198419194d.jpg','가오리된장찜','부식류 > 찜 및 선류 > 찜 > 어패류',null,'가열하여 익히는 음식 > 물을 이용한 음식 > 수증기로 찌는 음식');
Insert into FOOD.FOOD_TBL (ID,COOKING_INSTRUCTION,INGREDIENT,MINOR_INGREDIENT,REFERENCE,COOK,COOKING_ORIGIN,FOOD_IMG,FOOD_NAME,FOOD_TYPE,INFORMATION_PROVIDER,RECIPE) values (10,'1. 가오리는 내장을 빼고 소금물에 씻은 다음 물기를 빼고 햇볕에서 1~2일간 꾸덕꾸덕하게 말려 찜통에 넣고 찐다. 2. 통깨를 뿌리고 초고추장을 곁들인다.','가오리 1마리,통깨 약간','[초고추장] 고추장 3큰술, 식초3큰술, 설탕 1큰술, 다진 마늘 1작은술, 통깨 1작은술','·5가지 색으로 고명을 하기도 한다. ·양념장(간장, 청주, 설탕, 다진 파, 다진 마늘)에 재워 쪄 내기도 한다. ·큰상차림에 이용할 때는 통째로 양념장에 재워 그대로 쪄 낸다.',null,'경상남도 농촌진흥원, 경남향토음식, 1994 농촌진흥청 농촌영양개선연수원(현 농촌자원개발연구소), 한국의 향토음식, 1994','17f7a2a2-3f3d-41e8-8014-298d6697e501.jpg','가오리찜','부식류 > 찜 및 선류 > 찜 > 어패류',null,'가열하여 익히는 음식 > 물을 이용한 음식 > 수증기로 찌는 음식');
Insert into FOOD.FOOD_TBL (ID,COOKING_INSTRUCTION,INGREDIENT,MINOR_INGREDIENT,REFERENCE,COOK,COOKING_ORIGIN,FOOD_IMG,FOOD_NAME,FOOD_TYPE,INFORMATION_PROVIDER,RECIPE) values (11,'1. 가오리는 깨끗이 손질하여 4등분하고 2~3일 정도 꾸덕꾸덕하게 말린다. 2. 말린 가오리에 양념장을 발라 4~6시간 정도 재운다. 3. 김이 오른 찜통에 면포를 깔고 재워 둔 가오리를 넣어 30분 정도 찐 후 완전히 식으면 잘라 참기름을 살짝 바르고 통깨, 실고추를 뿌린다.','참기름 1큰술, 통깨 1큰술, 실고추 약간, 가오리 2kg(1마리)','[양념장] 간장 5~6컵, 다진 마늘 2큰술, 다진 생강 1큰술, 설탕 1/2컵, 식용유 1/2컵, 참기름 2큰술, 후춧가루 약간','말린 가오리를 찜기에 쪄서 초고추장을 곁들이기도 한다.','신영자, 경상북도 영양군','구미시농업기술센터, 구미향토-로하스요리 질시루, 2005','be34c3e7-3a67-4f31-855b-14d9ace31fdd.jpg','가오리찜','부식류 > 찜 및 선류 > 찜 > 어패류',null,'가열하여 익히는 음식 > 물을 이용한 음식 > 수증기로 찌는 음식');
Insert into FOOD.FOOD_TBL (ID,COOKING_INSTRUCTION,INGREDIENT,MINOR_INGREDIENT,REFERENCE,COOK,COOKING_ORIGIN,FOOD_IMG,FOOD_NAME,FOOD_TYPE,INFORMATION_PROVIDER,RECIPE) values (12,'1. 가오리를 깨끗하게 손질하여 하루 정도 말려서 길이 5cm, 너비 2cm 크기로 썬다. 2. 가오리를 송송 썬 실파, 다진 마늘, 참기름, 소금으로 양념한다. 3. 양념한 가오리를 찜솥에 넣고 찐 후 실고추를 얹어서 낸다.','가오리 (갱개미) 1kg(1마리), 실고추 약간','[양념] 실파 50g, 다진 마늘 1큰술, 참기름 1큰술, 소금 1큰술','서해안에서 즐겨 먹는 가오리(갱개미)는 홍어와 비슷하며, 회로도 먹고 찜으로도 애용되는 음식이다.',null,null,'blank_image.png','가오리찜(갱개미찜)','부식류 > 찜 및 선류 > 찜 > 어패류',null,'가열하여 익히는 음식 > 물을 이용한 음식 > 수증기로 찌는 음식');
Insert into FOOD.FOOD_TBL (ID,COOKING_INSTRUCTION,INGREDIENT,MINOR_INGREDIENT,REFERENCE,COOK,COOKING_ORIGIN,FOOD_IMG,FOOD_NAME,FOOD_TYPE,INFORMATION_PROVIDER,RECIPE) values (3,'1. 갈비를 5-6cm길이로 잘라 손질하여 핏물을 빼고, 무는 통으로 3cm두께로 잘라서 물을 부어 5-6시간 푹 곤다. 2. 무는 처음부터 넣어서 중간에 건져 낸다. 3. 갈비의 살이 무르게 익으면 건져 내어 국간장, 다진 파, 다진 마늘, 참기름, 후춧가루, 깨소금을 잘 섞어서 양념하고 국물은 식혀서 굳은 기름은 제거한다. 4. 무는 건져 2.5×3×0.5cm의 직사각형 모양으로 썰고, 대파는 굵게 썰어 갈비와 함께 섞은 후 국물에 다시 넣어서 끓인다. 5. 달걀은 황백으로 나누어 각각 지단을 부쳐 채를 썬다 (5×0.2×0.2cm). 6. 간을 맞춰서 그릇에 담고 황백지단을 올린다.','갈비 2kg, 무 300g(1/3개), 물 5L(25컵), 대파 20g(½뿌리), 달걀 50g(1개)','<양념> 국간장 3큰술, 다진 파 2작은술, 다진 마늘 2작은술, 참기름 1작은술, 후춧가루 1/4작은술, 깨소금 1작은술',null,null,'문화공보부 문화재관리국, 한국민속종합조사보고서(향토음식편), 1984','blank_image.png','가리탕(갈비탕)','부식류 > 국 및 탕류 > 곰국 및 탕 > 육류',null,'가열하여 익히는 음식 > 물을 이용한 음식 > 끓이는 음식');
Insert into FOOD.FOOD_TBL (ID,COOKING_INSTRUCTION,INGREDIENT,MINOR_INGREDIENT,REFERENCE,COOK,COOKING_ORIGIN,FOOD_IMG,FOOD_NAME,FOOD_TYPE,INFORMATION_PROVIDER,RECIPE) values (4,'1. 팥은 깨끗이 씻어 삶아 건진다. 2. 호두는 잘게 다진다. 3. 삶은 팥, 다진 호두, 잣에 꿀을 넣어 섞는다. 4. 밀가루에 소금을 넣고 체에 내린 다음 물을 넣고 반죽한다. 5. 가열한 팬에 식용유를 두르고 4의 반죽을 한 국자씩 떠 넣어 전병을 부친다. 6. 전병에 3을 1~2큰술씩 올리고 말아서 지진다.','밀가루 330g(3컵), 팥 105g(1/2컵), 호두(깐 것) 50g(5개), 잣 1큰술 , 물 550mL(2 3/4컵), 꿀 2큰술, 소금 1/2작은술, 식용유 1/2큰술',null,null,null,'구미시농업기술센터, 구미 향토-로하스요리 질시루, 2005','f2eb27ec-9a64-4ef8-bec9-01cf1e585fd6.jpg','가마니떡(밀주머니떡)','떡류 > 떡류 > 지지는 떡 > 지지는 떡',null,'가열하여 익히는 음식 > 기름을 이용하여 익히는 음식 > 기름을 이용하여 익히는 음식');
Insert into FOOD.FOOD_TBL (ID,COOKING_INSTRUCTION,INGREDIENT,MINOR_INGREDIENT,REFERENCE,COOK,COOKING_ORIGIN,FOOD_IMG,FOOD_NAME,FOOD_TYPE,INFORMATION_PROVIDER,RECIPE) values (5,'1. 가물치는 내장을 제거하고 깨끗이 씻는다. 2. 들기름을 두른 솥에 손질한 가물치를 넣고 물을 부어 센 불로 끓인다. 3. 2가 끓으면 중불로 낮춰 뼈가 물렁해질 때까지 푹 곤다. 4. 그릇에 3을 담고 소금을 곁들인다.','가물치 2마리, 물 8L(40컵), 들기름 1큰술, 소금 약간',null,'찹쌀, 생강, 대추, 미나리, 대파, 마늘, 깨소금을 넣어 탕을 만들기도 한다.',null,null,'119a4f2d-f0da-4efe-ac1b-8a84e4a9d4f3.jpg','가물치곰국','부식류 > 국 및 탕류 > 곰국 및 탕 > 어패류',null,'가열하여 익히는 음식 > 물을 이용한 음식 > 끓이는 음식');
Insert into FOOD.FOOD_TBL (ID,COOKING_INSTRUCTION,INGREDIENT,MINOR_INGREDIENT,REFERENCE,COOK,COOKING_ORIGIN,FOOD_IMG,FOOD_NAME,FOOD_TYPE,INFORMATION_PROVIDER,RECIPE) values (1,'1. 돼지고기는 5×5×0.3cm 크기로 썬 후 굵은 소금을 조금씩 뿌려 가며 숯불에서 살짝 익혀 기름을 뺀다. 2. 양파는 굵게 채 썰고(5×0.3×0.3cm), 풋고추는 0.3cm 두께로 어슷썰기 한다. 3. 준비된 돼지고기, 양파, 풋고추에 양념장을 넣어 재운다. 4. 3을 숯불에서 타지 않도록 한번 더 굽는다.','돼지고기(목살) 600g, 양파 160g(1개), 풋고추 45g(3개), 굵은 소금 약간','<양념장> 간장 4큰술, 설탕 2큰술, 다진 마늘 1/2큰술, 다진 파 1큰술, 고춧가루 1큰술, 깨소금 1큰술, 참기름 1작은술, 후춧가루 약간','돼지고기는 쉽게 상하므로 가례마을에서는 숯불에 살짝 익혀서 저장하였다가 먹을 때 양념하여 다시 구워 먹었던 것에서 유래되었다.',null,'의령군농업기술센터, 의령의 맛, 2002','blank_image.png','가례불고기','부식류 > 구이류 > 구이류 > 육류',null,'가열하여 익히는 음식 > 굽는 음식 > 굽는 음식');
Insert into FOOD.FOOD_TBL (ID,COOKING_INSTRUCTION,INGREDIENT,MINOR_INGREDIENT,REFERENCE,COOK,COOKING_ORIGIN,FOOD_IMG,FOOD_NAME,FOOD_TYPE,INFORMATION_PROVIDER,RECIPE) values (2,'1. 새우와 다슬기는 삶아 껍질을 벗겨 살만 발라 내고, 육수도 따로 둔다. 2. 방아잎은 씻어 뜯어 놓고, 풋고추는 송송 썬다(0.3cm). 3. 육수에 밀가루를 풀고 손질한 새우와 다슬기를 넣어 저어 가면서 끓인 다음 걸쭉해지면 방아잎을 넣는다. 4. 국간장으로 간을 맞추고 들깻가루와 다진 마늘을 넣는다.','해물(새우, 다슬기) 200g, 밀가루 110g(1컵), 방아잎 50g, 풋고추 30g(2개), 물 800mL(4컵), 들깻가루 1큰술, 국간장 1큰술, 다진 마늘 1큰술',null,'·남해의 토속음식으로 모내기 전후 우렁이가 잡힐 때나 보통 제사 때 각종 나물에 이용하기도 한다. 우렁이 대신에 다슬기나 참게 등을 이용하기도 한다. ·밀가루 대신 찹쌀가루, 맵쌀가루를 이용하기도 하고, 고추장으로 간을 하기도 한다.',null,'남해군농업기술센터, 보물섬 남해 향토 먹거리 맛과 멋, 2005','ebc0f30f-07fa-4e55-9b05-26a2caba95de.jpg','가루장국(가리장국)','부식류 > 국 및 탕류 > 맑은국',null,'가열하지 않는 음식 > 소금이나 장류에 절이는 음식 > 소금이나 장류에 절이는 음식');
Insert into FOOD.FOOD_TBL (ID,COOKING_INSTRUCTION,INGREDIENT,MINOR_INGREDIENT,REFERENCE,COOK,COOKING_ORIGIN,FOOD_IMG,FOOD_NAME,FOOD_TYPE,INFORMATION_PROVIDER,RECIPE) values (6,'1. 가물치는 손질하여 물을 붓고 3시간 정도 약한 불에서 푹 곤다. 2. 찹쌀은 깨끗이 씻어 30분 정도 물에 불린다. 3. 미나리는 다듬어 5cm길이로 썰고, 대파는 어슷썬다(0.3cm) 4. 생강은 얇게 편 썰고(0.3cm), 대추와 인삼은 깨끗이 씻어 둔다. 5. 1을 체에 밭쳐 찌꺼지는 버리고 받은 국물에 찹쌀, 생강, 대추, 인삼을 넣고 끓인다. 6. 찹쌀이 어느 정도 익으면 미나리, 어슷썬 대파, 다진 마늘, 다진 생강, 깨소금, 소금을 넣어 한소끔 끓인다.','가물치 1마리, 찹쌀 330g(2컵), 미나리 50g, 대파 35g(1뿌리), 생강 20g(5쪽), 대추 20g(10개), 인삼 2뿌리, 다진 마늘 5큰술, 다진 생강 3큰술, 깨소금 3큰술, 물 적량, 소금 적량',null,'·예로부터 이뇨제로 작용한다 하여 결석 환자에게 특효제로서 작용하였고 보양제로서 널리 각광을 받고 있다. ·탕을 먹고 나서 계피를 이용하여 만든 수정과를 마시면 뒷맛이 개운해 진다.',null,'농촌진흥청 농촌영양개선연수원(현 농촌자원개발연구소), 한국의 향토음식, 1994','6f2c0f86-c9a8-412b-9897-033564d880ca.jpg','가물치곰탕','부식류 > 국 및 탕류 > 곰국 및 탕 > 어패류',null,'가열하여 익히는 음식 > 물을 이용한 음식 > 끓이는 음식');
Insert into FOOD.FOOD_TBL (ID,COOKING_INSTRUCTION,INGREDIENT,MINOR_INGREDIENT,REFERENCE,COOK,COOKING_ORIGIN,FOOD_IMG,FOOD_NAME,FOOD_TYPE,INFORMATION_PROVIDER,RECIPE) values (90,'1. 멥쌀가루는 소금을 넣고 고운체에 내린다. 2. 감고지는 물에 씻어서 설탕(1/4컵)을 넣어 섞는다. 3. 밤은 4~6등분으로 썰고, 대추는 씨를 발라 내 4~6 조각으로 썬다. 4. 준비된 재료에 설탕(1컵)을 넣어 고루 섞는다. 5. 김이 오른 찜통에 면포를 깔고 4를 안쳐서 30분 정도 찐다.','멥쌀가루 1.7kg(11컵), 감고지 160g, 밤(깐 것) 100g(10개), 대추 160g(2 1/3컵), 설탕 1 1/4컵, 소금 1큰술',null,null,null,'청도군농업기술센터, 청도 향토음식의 보고 석빙고, 2004','blank_image.png','감고지떡(감모름떡)','떡류 > 떡류 > 찌는 떡 > 찌는 떡',null,'가열하여 익히는 음식 > 물을 이용한 음식 > 수증기로 찌는 음식');
Insert into FOOD.FOOD_TBL (ID,COOKING_INSTRUCTION,INGREDIENT,MINOR_INGREDIENT,REFERENCE,COOK,COOKING_ORIGIN,FOOD_IMG,FOOD_NAME,FOOD_TYPE,INFORMATION_PROVIDER,RECIPE) values (91,'1. 홍시조청에 뜨거운 물을 넣어 풀어 준 후 식힌다. 2. 1에 고춧가루와 메줏가루, 소금을 넣어 고루 섞는다.','홍시조청 600g, 물 200mL(1컵), 고춧가루 200g(2 1/2컵), 메줏가루 50g(2/3컵), 소금 1/3컵',null,'홍시조청은 잘 익은 홍시를 씻어 끓인 후 건더기는 걸러 낸다. 남은 국물을 엿기름에 삭혀 약한 불에서 끈기가 생길때까지 저어 가며 조린다.',null,'청도군농업기술센터, 청도향토음식의 보고 석빙고, 2004 네이버사전(두산백과), 100.naver.com/,2006','blank_image.png','감고추장','발효식품류 > 장류 > 고추장류 > 고추장류',null,'가열하지 않는 음식 > 소금이나 장류에 절이는 음식 > 소금이나 장류에 절이는 음식');
Insert into FOOD.FOOD_TBL (ID,COOKING_INSTRUCTION,INGREDIENT,MINOR_INGREDIENT,REFERENCE,COOK,COOKING_ORIGIN,FOOD_IMG,FOOD_NAME,FOOD_TYPE,INFORMATION_PROVIDER,RECIPE) values (92,'1. 잘 익고 단단한 감을 반으로 갈라 0.5cm 두께로 썰어 햇볕에 꼬들꼬들하게 말린 후 소금물에 깨끗이 씻어 건진다. 2. 새우와 굴은 소금물에 깨끗이 씻어 물기를 뺀다. 3. 미나리와 실파는 5cm 길이로 썬다. 4. 무는 곱게 채 썰고(5×0.2×0.2cm), 대파는 어슷썰고 고춧가루를 넣고 버무려서 붉은 색을 들인 후 미나리와 실파를 넣어서 버무린다. 5. 4에 양념, 새우와 굴을 넣고 버무린 다음 감을 넣고 버무려 항아리에 담고 1주일 정도 숙성시킨다.','감 5kg(30개), 무 850g(1개), 대파 60g(2뿌리), 미나리 50g, 실파 50g, 굴 50g, 새우 50g, 굵은 소금 1컵, 고춧가루 1컵, 물 적량','[양념] 멸치젓 1컵, 다진 마늘 3큰술, 다진 생강 1큰술, 고운 소금 1/3컵, 설탕 약간','배추를 같이 넣기도 한다.',null,'상주시농업기술센터, 상주 향토음식 맥잇기 고운 빛 깊은 맛, 2004','42bb8476-060a-4894-a7ca-98134f7ebcfe.jpg','감김치','부식류 > 김치류 > 김치류 > 기타',null,'가열하지 않는 음식 > 소금이나 장류에 절이는 음식 > 소금이나 장류에 절이는 음식');
Insert into FOOD.FOOD_TBL (ID,COOKING_INSTRUCTION,INGREDIENT,MINOR_INGREDIENT,REFERENCE,COOK,COOKING_ORIGIN,FOOD_IMG,FOOD_NAME,FOOD_TYPE,INFORMATION_PROVIDER,RECIPE) values (93,'1. 여뀟대(약국대)는 삶아 건져 내고 물은 차게 식힌다. 2. 감은 씻어 항아리에 넣고 감이 잠길 정도로 여뀟대 삶은 물을 붓고 소금을 뿌린다. 3. 2에 짚과 여뀟대를 덮고 뚜껑을 덮어 서늘한 곳에 보관한다.','땡감 100개, 소금 3컵, 여뀟대(약국대) , 짚 적량',null,null,null,'울산광역시농업기술센터, 울산향토음식, 2001 이연정 · 하미옥 · 최수근, 울산지역 향토음식에 대한 식행동과 기호도에 관한 연구, 한국식생활문화학회지, 21(5), 2006','53337eae-50e1-4f88-92f5-eb08922ef92c.jpg','감김치','부식류 > 김치류 > 김치류 > 기타',null,'가열하지 않는 음식 > 소금이나 장류에 절이는 음식 > 소금이나 장류에 절이는 음식');
Insert into FOOD.FOOD_TBL (ID,COOKING_INSTRUCTION,INGREDIENT,MINOR_INGREDIENT,REFERENCE,COOK,COOKING_ORIGIN,FOOD_IMG,FOOD_NAME,FOOD_TYPE,INFORMATION_PROVIDER,RECIPE) values (94,'1. 감잎과 감꽃은 씻어 물기를 뺀다. 2. 냄비에 찹쌀가루와 물을 붓고 찹쌀풀을 끓인 후 소금으로 간을 하여 식힌다. 3. 감잎은 앞면에만 찹쌀풀을 바르고 감꽃은 적셔 말린다. 찹쌀풀 바르는 과정을 2회 정도 반복한다. 4. 3의 감잎과 감꽃을 170℃의 식용유에서 재빨리 튀겨 낸다.','감잎 60장,감꽃 약간,찹쌀가루 200g(2컵),물 600mL(3컵),소금 2작은술,식용유 적량',null,'6~7월에 감잎을 따서 부각을 만든다.',null,'청도군농업기술센터, 청도향토음식의 보고 석빙고, 2004','blank_image.png','감꽃부각(감잎부각)','부식류 > 마른찬류 > 부각 > 기타',null,'가열하여 익히는 음식 > 기름을 이용하여 익히는 음식 > 기름을 이용하여 익히는 음식');
Insert into FOOD.FOOD_TBL (ID,COOKING_INSTRUCTION,INGREDIENT,MINOR_INGREDIENT,REFERENCE,COOK,COOKING_ORIGIN,FOOD_IMG,FOOD_NAME,FOOD_TYPE,INFORMATION_PROVIDER,RECIPE) values (95,'1. 감은 꼭지를 따고 깨끗이 씻어 물(3컵)을 붓고 푹 고은 후 체에 밭쳐 거른다. 2. 생강은 껍질을 벗겨 물(1/2컵)을 붓고 물의 양이 반으로 될 때까지 고아 체에 거른다. 3. 찹쌀가루에 감물 6큰술, 생강물, 계핏가루, 설탕을 고루 섞어 김이 오른 찜통에 면포를 깔고 찐 후 절구에 담아 치댄다. 4. 치댄 떡 양쪽에 동부고물을 묻혀 적당한 크기로 썬다.','떫은 감 2kg(13개), 찹쌀가루 500g(5컵), 동부고물 400g(2컵), 계핏가루 30g, 생강 20g(1톨), 설탕 250g(1 2/3컵), 물 700mL(3 1/2컵)',null,null,null,'경상남도 농촌진흥원, 경남향토음식, 1994 농촌진흥청 농촌영양개선연수원(현 농촌자원개발연구소), 한국의 향토음식, 1994 농촌진흥청 농촌생활연구소(현 농촌자원개발연구소), 전통지식 모음집(생활문화 편), 1997','blank_image.png','감단자','떡류 > 떡류 > 치는 떡 > 치는 떡',null,'가열하여 익히는 음식 > 물을 이용한 음식 > 수증기로 찌는 음식');
Insert into FOOD.FOOD_TBL (ID,COOKING_INSTRUCTION,INGREDIENT,MINOR_INGREDIENT,REFERENCE,COOK,COOKING_ORIGIN,FOOD_IMG,FOOD_NAME,FOOD_TYPE,INFORMATION_PROVIDER,RECIPE) values (96,'1. 감은 꼭지를 따고 깨끗이 씻어 물을 부어 푹 곤 다음 체에 거른다. 2. 생강은 편으로 썰어 물을 붓고 끓여 생강물을 만든다. 3. 냄비에 생강물을 붓고 으깬 감, 설탕, 소금을 넣고 섞는다. 4. 3에 찹쌀가루를 넣고 빠르게 저으면서 끓인다. 5. 찹쌀이 익고 덩어리가 지면 꺼내어 식힌다. 6. 5를 적당한 크기로 떼어 모양을 만들어 팥고물을 묻힌다.','감 1.3kg(10개), 찹쌀가루 500g(5컵), 생강 50g, 팥고물 3컵, 설탕 5큰술, 물 적량, 소금 약간',null,'·찹쌀가루에 감즙과 생강즙을 넣어 찜솥에 넣고 찐 다음 쳐서 고물을 묻히는 방법도 있다. ·홍시나 고욤(작은 감)을 가지고 만든다. 홍시는 굵은체에 거르고 무르지 않은 감은 삶아서 거른다. ·감단자는 감과 찹쌀을 이용한 전통음식으로 일반 떡이 쉽게 노화되는 데 비하여 오랫동안 호화 상태가 유지되어 부드럽고 소화도 잘 되는 영양식이다.','정정희, 전라북도 전주시 덕진구 금암1동',null,'1dc86bae-fdea-4263-90f9-af3192f18b48.jpg','감단자','떡류 > 떡류',null,'가열하여 익히는 음식 > 물을 이용한 음식 > 끓이는 음식');
Insert into FOOD.FOOD_TBL (ID,COOKING_INSTRUCTION,INGREDIENT,MINOR_INGREDIENT,REFERENCE,COOK,COOKING_ORIGIN,FOOD_IMG,FOOD_NAME,FOOD_TYPE,INFORMATION_PROVIDER,RECIPE) values (97,'1. 홍시를 체에 내린다. 2. 체에 내린 홍시를 냄비에 넣고 나무주걱으로 저으면서 찹쌀가루를 넣고 조린다. 3. 2를 쟁반에 펴서 식힌 다음 동글납작하게 빚는다. 4. 동부고물을 묻혀 낸다.','홍시 840g(6개), 동부고물 5컵, 찹쌀가루 800g(8컵)',null,null,'조경자, 전라남도 광양시',null,'c9fd7493-4396-4b43-ba45-d9aae3ca7336.jpg','감단자','떡류 > 떡류','전순엽, 전라남도 광양시','가열하여 익히는 음식 > 물을 이용한 음식 > 수증기로 찌는 음식');
Insert into FOOD.FOOD_TBL (ID,COOKING_INSTRUCTION,INGREDIENT,MINOR_INGREDIENT,REFERENCE,COOK,COOKING_ORIGIN,FOOD_IMG,FOOD_NAME,FOOD_TYPE,INFORMATION_PROVIDER,RECIPE) values (85,'1. 갈치는 은비늘이 붙은 상태에서 지느러미와 내장을 제거하고 10cm정도의 길이로 토막을 낸다. 2. 늙은 호박은 껍질을 벗기고 씨를 긁어 낸 다음 도톰하게 썰고, 배추는 깨끗이 씻어 적당한 크기로 썬다. 3. 풋고추, 붉은 고추, 대파는 어슷썬다(0.3cm). 4. 물이 끓기 시작하면 토막 낸 갈치를 넣어 한소끔 끓인 후 호박과 배추를 넣어 다시 끓인다. 5. 풋고추, 붉은 고추, 대파, 다진 마늘을 넣고 국간장으로 간을 한다.','갈치 320g(1마리), 늙은 호박 100g, 어린 배추 적량, 풋고추 30g(2개), 붉은 고추 30g(2개), 물 1.2L(6컵), 다진 파 2작은술, 다진 마늘 2작은술, 국간장 2큰술',null,'호박과 갈치는 잘 어울리는 식품이며 여름철에는 호박 대신 어린 배추를 넣어도 맛이 좋다.',null,'농촌진흥청 농촌영양개선연수원(현 농촌자원개발연구소), 한국의 향토음식, 1994 제주도 농촌진흥원, 오랫동안 전하여온 맛과 멋-제주 전통음식, 1995 제주음식연구회, 제주의 먹거리 모음, 2001 제주시농업기술센터, 제주 전통음식, 2003 제주특별자치도 농업기술원, 제주 전통음식, 2007 농촌진흥청, 향토음식, www2.rda.go.kr/food/, 2006','586f954d-fc07-4716-9a18-87fd0c37d5a4.JPG','갈치호박국(갈치국)','부식류 > 국 및 탕류 > 맑은국 > 어패류',null,'가열하여 익히는 음식 > 물을 이용한 음식 > 끓이는 음식');
Insert into FOOD.FOOD_TBL (ID,COOKING_INSTRUCTION,INGREDIENT,MINOR_INGREDIENT,REFERENCE,COOK,COOKING_ORIGIN,FOOD_IMG,FOOD_NAME,FOOD_TYPE,INFORMATION_PROVIDER,RECIPE) values (86,'1. 갈치는 포를 떠서 4~5cm 크기로 썰어 여러 번 헹군다. 2. 미나리는 5cm 길이로 썰고, 양파와 배는 곱게 채 썬다(5×0.2×0.2cm). 3. 풋고추는 어슷썰기 하고, 쑥갓은 잎을 뜯어 놓는다. 4. 준비된 모든 재료에 양념장을 넣어 버무린다.','갈치 320g(1마리), 미나리 100g, 양파 80g(1/2개), 쑥갓 50g, 풋고추 30g(2개), 배 60g','<양념> 고추장 3큰술, 식초 3큰술, 설탕 1큰술, 다진 마늘 1작은술, 통깨 1작은술','·기장 갈치는 통일신라시대부터 유명하여 왕에게 진상되고 귀족에게 상납하는 생선이었다. 가을에 맛이 제일 좋아 가을갈치라 하며, 구이, 자반, 조림, 젓 등의 다양한 음식이 있다. 어묵 제조 시에도 갈치 살이 들어가면 맛이 있다. ·잔 갈치는 뼈째 채 썰어 이용한다. ·갈치비늘은 호박잎을 이용하면 깨끗이 벗겨진다. ·갈치회는 기름기와 비늘을 씻어 낸 후 막걸리로 헹궈 물기를 마른 면포로 제거하여 이용한다. ·갈치와 채소를 버무리지 않고 따로 내고 초고추장이나 고추냉이간장을 곁들이기도 한다.',null,'기장군농업기술센터, 기장의 향토음식, 2003 남해군농업기술센터, 보물섬남해 향토먹거리 맛과 멋, 2005 신애숙, 부산의 전통, 향토음식의 현황 고찰, 한국조리학회지, 6(2), 2000','blank_image.png','갈치회(기장갈치회)','부식류 > 회류 > 무침 > 어패류','공득선, 부산광역시 기장군 기장읍 동부리<br>','가열하지 않는 음식 > 날것에 조미료를 곁들여 먹는 음식 > 날것에 조미료를 곁들여 먹는 음식');
Insert into FOOD.FOOD_TBL (ID,COOKING_INSTRUCTION,INGREDIENT,MINOR_INGREDIENT,REFERENCE,COOK,COOKING_ORIGIN,FOOD_IMG,FOOD_NAME,FOOD_TYPE,INFORMATION_PROVIDER,RECIPE) values (87,'1. 돼지뼈에 물을 붓고 푹 고아서 국물을 낸다. 2. 마른 갈파래는 물에 담가 불린다. 3. 국물에 된장을 풀고 갈파래를 넣어 끓이고 다진 풋고추와 붉은 고추, 고춧가루, 다진 마늘을 넣어 다시 한 번 끓인다.','마른 갈파래 100g, 돼지뼈 1kg, 된장 4큰술, 다진 풋고추 2큰술, 다진 붉은 고추 2큰술, 고춧가루 1/2큰술(또는 고추씨가루 1큰술), 물 적량, 다진 마늘 약간',null,'전남 신안군 하의도에서 잔칫날이나 상갓집에서 가마솥에 가득 끓여 놓고 떠 먹는 향토음식이다.','제갈향덕, 전라남도 신안군 하의도',null,'5fee4000-7242-42e9-9f18-333ed785f124.jpg','갈파래국','부식류 > 국 및 탕류 > 토장국 > 해조류','김은경, 전라남도 목포시 용당 1동','가열하여 익히는 음식 > 물을 이용한 음식 > 끓이는 음식');
Insert into FOOD.FOOD_TBL (ID,COOKING_INSTRUCTION,INGREDIENT,MINOR_INGREDIENT,REFERENCE,COOK,COOKING_ORIGIN,FOOD_IMG,FOOD_NAME,FOOD_TYPE,INFORMATION_PROVIDER,RECIPE) values (88,'1. 생강은 얇게 편 썰기 하여 냄비에 넣고 물 1컵을 부은 다음 끓여 진하게 생강물을 우려 낸다. 2. 홍시는 칼집을 넣은 후 껍질을 벗기고 물 1/2컵을 넣고 삶아 체에 내린다. 3. 찹쌀가루에 소금 1작은술을 넣고 생강물 2큰술, 홍시물 5큰술, 계핏가루를 넣어서 익반죽한다. 4. 3을 밤톨 크기 정도로 떼어 동그랗게 빚는다. 5. 냄비에 물을 붓고 소금(1/2작은술)을 넣어 끓이다가 4의 경단을 한 개씩 넣고 떠오르면 건져 내어 찬물에 씻어 물기를 뺀다. 6. 5에 녹두고물을 묻힌다.','찹쌀가루 550g(5 1/2컵), 녹두고물 115g(1컵), 홍시 2개, 생강 50g(1/2컵), 소금 1 1/2작은술, 물 300ml(1 1/2컵), 계핏가루 약간',null,null,'박미숙, 경상북도 경주시 내남면 이조리',null,'65e9b64d-c7e5-4698-9ab8-64ef22807c8b.jpg','감경단','떡류 > 떡류 > 삶는 떡(경단류) > 삶는 떡(경단류)',null,'가열하여 익히는 음식 > 물을 이용한 음식 > 끓이는 음식');
Insert into FOOD.FOOD_TBL (ID,COOKING_INSTRUCTION,INGREDIENT,MINOR_INGREDIENT,REFERENCE,COOK,COOKING_ORIGIN,FOOD_IMG,FOOD_NAME,FOOD_TYPE,INFORMATION_PROVIDER,RECIPE) values (89,'1. 감은 껍질을 벗겨 0.5cm 두께로 썰어 꾸덕꾸덕하게 말린다. 2. 멥쌀가루에 끓여 식힌 설탕물을 넣어 고루 비빈 다음 체에 내린다. 3. 녹두를 하룻밤 불려 껍질을 벗긴 다음 씻어 김이 오른 찜통에 젖은 면포를 덮고 뚜껑을 덮어 찐다. 손으로 문질러 보아 으깨지면 다 쪄진 것이다. 4. 뜨거울 때 녹두에 소금을 넣어 절구에 찧고 체에 내려 고물을 만든다. 5. 멥쌀가루에 꾸덕꾸덕하게 말린 감고지를 섞어 놓는다. 6. 시루에 시루밑을 깔고 녹두고물을 충분히 깐 후 쌀가루와 녹두고물을 켜켜로 안친다. 7. 밀가루를 반죽으로 김이 새지 않게 시룻번을 붙여 김이 오른 후 20분간 쪄낸다. 8. 젓가락을 찔러 보아 쌀가루가 묻어 나오지 않으면 다 익은 것이다.','감고지 600g, 멥쌀가루 2kg(20컵), 소금 2큰술, 설탕물 , 녹두고물','<설탕물> 설탕 1/2컵, 물 200m(1컵) <녹두고물> 녹두 800g(4컵), 소금 1큰술','시룻번은 밀가루에 반죽하여 가래떡처럼 길게 모양 내여 솥과 시루 사이에 물을 묻혀서 수증기가 새어 나오지 않게 눌러 붙이는 것이다.',null,'광주광역시농업기술센터, 미향 광주의 향토음식, 2003 장성군농업기술센터, 장성의 맛과 멋, 2003','blank_image.png','감고지떡','떡류 > 떡류 > 찌는 떡 > 찌는 떡',null,'가열하여 익히는 음식 > 물을 이용한 음식 > 수증기로 찌는 음식');
Insert into FOOD.FOOD_TBL (ID,COOKING_INSTRUCTION,INGREDIENT,MINOR_INGREDIENT,REFERENCE,COOK,COOKING_ORIGIN,FOOD_IMG,FOOD_NAME,FOOD_TYPE,INFORMATION_PROVIDER,RECIPE) values (78,'1. 봄에 싱싱한 갈치의 속을 꺼내어 즉시 소금을 넣고 버무려 항아리에 담은 후 여름까지 보관한다. 2. 갈치속젓에 송송 썬(0.5cm) 풋고추와 고춧가루, 다진 파, 참기름, 깨소금을 넣어 무쳐 먹는다.','갈치 , 소금 적량','<양념> 풋고추 15g(1개), 고춧가루 2큰술, 다진 파 1작은술, 다진 마늘 1작은술, 참기름 1작은술, 깨소금 1작은술','갈치의 식도에서 창자까지 하나도 버리지 않고 내장만으로 담갔다고 하여 속젓이라 한다.',null,'문화공보부 문화재관리국, 한국민속종합조사보고서(전라남도편), 1968 전라남도 농촌진흥원, 향토요리모음, 1979','blank_image.png','갈치속젓','부식류 > 젓갈 및 식해류 > 젓갈 > 젓갈','최재순, 전라남도 신안군 자은면 남진리<br>','가열하지 않는 음식 > 소금이나 장류에 절이는 음식 > 소금이나 장류에 절이는 음식');
Insert into FOOD.FOOD_TBL (ID,COOKING_INSTRUCTION,INGREDIENT,MINOR_INGREDIENT,REFERENCE,COOK,COOKING_ORIGIN,FOOD_IMG,FOOD_NAME,FOOD_TYPE,INFORMATION_PROVIDER,RECIPE) values (79,'1. 갈치는 소금물에 절여 하룻밤 재운 후 물기를 빼고 4~5cm 크기로 자른다. 2. 무는 5cm 길이로 채 썰어 소금에 절여 물기를 뺀다. 3. 쌀은 깨끗이 씻어 30분 정도 불린 후 고슬고슬하게 밥을 짓는다. 4. 준비된 무와 고춧가루를 함께 버무려 붉은 색이 나면 1의 갈치와 밥, 엿기름가루, 식해 양념을 넣고 버무린다. 5. 항아리에 꾹꾹 눌러 담아 3~4일간 따뜻한 곳에서 삭힌다.','갈치 650g(2마리), 쌀 180g(1컵), 무 300g(1/3개), 엿기름가루 100g(1컵), 소금 1컵, 물 200mL(1컵)','[식해 양념] 고춧가루 1컵, 소금 2큰술, 다진 파 2큰술, 다진 마늘 1큰술, 참기름 1큰술, 다진 생강 1작은술, 설탕 약간','식해에는 조기, 가자미, 명태(북어), 오징어 등이 이용된다.',null,null,'blank_image.png','갈치식해','부식류 > 젓갈 및 식해류 > 식해 > 식해',null,'가열하지 않는 음식 > 소금이나 장류에 절이는 음식 > 소금이나 장류에 절이는 음식');
Insert into FOOD.FOOD_TBL (ID,COOKING_INSTRUCTION,INGREDIENT,MINOR_INGREDIENT,REFERENCE,COOK,COOKING_ORIGIN,FOOD_IMG,FOOD_NAME,FOOD_TYPE,INFORMATION_PROVIDER,RECIPE) values (80,'1. 갈치의 이빨 부분을 자르고 칼집을 낸 다음 소금에 절여 항아리에 담는다. 2. 돌로 꼭 눌러 소금을 덮어 두었다가 한 겨울에 꺼내어 먹는다.','갈치(소) 2kg, 소금 2 1/2컵',null,'갈치를 곱게 다져서 양념을 하여 먹는다.',null,'제주특별자치도 농업기술원, 제주 전통음식, 2007','434c4367-a61d-482c-8653-1047e17e2260.jpg','갈치아가미젓(갈치알개미젓)','부식류 > 젓갈 및 식해류 > 젓갈 > 젓갈',null,'가열하지 않는 음식 > 소금이나 장류에 절이는 음식 > 소금이나 장류에 절이는 음식');
Insert into FOOD.FOOD_TBL (ID,COOKING_INSTRUCTION,INGREDIENT,MINOR_INGREDIENT,REFERENCE,COOK,COOKING_ORIGIN,FOOD_IMG,FOOD_NAME,FOOD_TYPE,INFORMATION_PROVIDER,RECIPE) values (81,'1. 갈치는 내장과 비늘을 제거하고 깨끗이 씻어 4~5cm 길이로 잘라 소금에 3~4일 정도 절인다. 2. 다진 마늘과 고춧가루는 따뜻한 물에 갠다. 3. 준비된 재료를 잘 버무린 후 초피잎을 넣어 섞은 후 1주일 정도 숙성시킨다.','갈치 1kg(3마리), 소금 200g(1 1/2컵), 고춧가루 2컵, 다진 마늘 1컵, 초피잎 (또는 초피가루) 약간, 물 100mL(1/2컵)',null,'·봄에는 초피잎을 다른 계절에는 초피가루를 이용한다. ·먹을 때 풋고추, 붉은 고추를 갈아서 넣기도 한다.','진한주, 경상남도 거제시 마전동','거제시농업기술센터, 거제향토음식, 1998 울산광역시농업기술센터, 울산향토음식, 2001','37177d33-2ae8-4ced-aa4e-d61252bbd538.jpg','갈치젓갈','부식류 > 젓갈 및 식해류 > 젓갈 > 젓갈','임경옥, 경상남도 기장군 기장읍 연화리','가열하지 않는 음식 > 소금이나 장류에 절이는 음식 > 소금이나 장류에 절이는 음식');
Insert into FOOD.FOOD_TBL (ID,COOKING_INSTRUCTION,INGREDIENT,MINOR_INGREDIENT,REFERENCE,COOK,COOKING_ORIGIN,FOOD_IMG,FOOD_NAME,FOOD_TYPE,INFORMATION_PROVIDER,RECIPE) values (82,'1. 갈치는 지느러미를 떼고 내장을 깨끗이 꺼내어 깨끗이 씻어 6cm 길이로 토막을 낸다. 2. 대파, 마늘, 생강은 씻어서 가늘게 채 썰어 나머지 양념과 섞어 양념장을 만든다. 3. 무는 납작하게 썰어(3×4×1cm) 냄비 바닥에 고르게 깔아 둔다. 4. 무 위에 양념장을 끼얹고 그 위에 갈치를 가지런히 놓은 다음 양념장을 고루 얹어 조린다. 5. 끓어오르면 불을 줄이고 양념장물을 떠서 위에 끼얹어 가면서 고루 간이 배도록 한다. 6. 무가 충분히 익고 갈치도 고루 간이 배면 불을 끈다.','갈치 200g(2/3마리), 무 100g(1/4개)','<양념장> 간장 35g(2큰술), 물 30mL(2큰술), 고춧가루 2g(1작은술), 대파 20g(1/2뿌리), 마늘 10g(2쪽), 생강 4g(1쪽), 설탕 6g(1/2큰술), 통깨 2g(1/2작은술)',null,null,'황혜성·한복려·한복진, 한국의 전통음식, 교문사, 1994 농촌진흥청 농업과학기술원 농촌생활연구소(현 농촌자원개발연구소), 소비자가 알기 쉬운 식품영양가표, 2002 서울특별시 교육청, 중·고등학생을 위한 학교급식 표준식단, 2002','blank_image.png','갈치조림(갈치무조림)','부식류 > 조림류 > 조림 > 어패류',null,'가열하여 익히는 음식 > 물을 이용한 음식 > 약간의 수분을 양념과함께 넣고 익혀 양념이 식품에 스며들게 하는 음식');
Insert into FOOD.FOOD_TBL (ID,COOKING_INSTRUCTION,INGREDIENT,MINOR_INGREDIENT,REFERENCE,COOK,COOKING_ORIGIN,FOOD_IMG,FOOD_NAME,FOOD_TYPE,INFORMATION_PROVIDER,RECIPE) values (83,'1. 갈치는 내장과 지느러미를 제거하고 네 토막 내어 깨끗이 씻는다. 2. 무는 납작하게 썰어(5×4×0.7)냄비 바닥에 깔고 그 위에 갈치와 양념장을 넣어 자작하게 조린다.','갈치 400g(1마리), 무 400g(1/2개)','<양념장> 간장 1/2컵, 물 1/2컵, 고춧가루 3큰술, 설탕 2작은술, 다진 마늘 1 1/2큰술, 생강즙 2작은술, 식용유 1큰술','무를 먼저 반 정도 익힌 다음 조리기도 한다.',null,'제주특별자치도 농업기술원, 제주 전통음식, 2007','blank_image.png','갈치조림(갈치지짐)','부식류 > 조림류 > 조림 > 어패류',null,'가열하여 익히는 음식 > 물을 이용한 음식 > 약간의 수분을 양념과함께 넣고 익혀 양념이 식품에 스며들게 하는 음식');
Insert into FOOD.FOOD_TBL (ID,COOKING_INSTRUCTION,INGREDIENT,MINOR_INGREDIENT,REFERENCE,COOK,COOKING_ORIGIN,FOOD_IMG,FOOD_NAME,FOOD_TYPE,INFORMATION_PROVIDER,RECIPE) values (84,'1. 갈치는 비늘을 긁어 내고 내장을 제거 한 후 5cm 길이로 자른다. 2. 애호박은 0.5cm 두께로 반달썰기 한다. 3. 붉은 고추와 대파는 어슷썰기 한다. 4. 냄비에 물을 부어 끓인 후 갈치와 애호박을 넣어 끓인다. 5. 4에 붉은 고추, 대파, 고춧가루, 다진 마늘을 넣고 한소끔 더 끓여 소금으로 간을 한다.','갈치 320g (1마리), 애호박 200g(1/2개), 붉은 고추 30g(2개), 대파 35g(1뿌리), 다진 마늘 1큰술, 고춧가루 1작은술, 소금 1작은술, 물 1.2L(6컵)',null,'·애호박은 간장에 절여 이용하기도 한다. ·늙은 호박을 이용하면 갈치늙은호박찌개라고 한다.',null,'울산광역시농업기술센터, 울산향토음식, 2001 기장군농업기술센터, 기장의 향토음식, 2003','57c0db46-8c5b-478d-8e31-f1a3b0257b8d.jpg','갈치찌개(갈치호박찌개)','부식류 > 전골 및 찌개류 > 찌개 > 어패류',null,'가열하여 익히는 음식 > 물을 이용한 음식 > 끓이는 음식');
Insert into FOOD.FOOD_TBL (ID,COOKING_INSTRUCTION,INGREDIENT,MINOR_INGREDIENT,REFERENCE,COOK,COOKING_ORIGIN,FOOD_IMG,FOOD_NAME,FOOD_TYPE,INFORMATION_PROVIDER,RECIPE) values (72,'1. 신선하고 밝은 은빛이 중간 크기의 갈치를 준비하여 내장을 뺀 다음 손질하여 7~8cm 길이로 토막을 낸 후 깨끗이 씻어 물기를 뺀다. 2. 손질한 갈치에 소금을 뿌려 간이 배도록 30분 정도 채반에 밭쳐 두었다가 소금을 털어 낸다. 3. 가열한 팬에 식용유를 두르고 갈치를 바삭하게 굽는다.','갈치 320g(1마리),소금 1큰술,식용유 1작은술',null,'석쇠에 굽기도 한다.',null,'문화공보부 문화재관리국, 한국민속종합조사보고서(향토음식 편), 1984 거제시농업기술센터, 거제향토음식, 1998 울산광역시농업기술센터, 울산향토음식, 2001 남해군농업기술센터, 보물섬남해 향토먹거리 맛과 멋, 2005','7724a9ed-1952-40f1-bc9f-378c705dc663.jpg','갈치구이','부식류 > 구이류 > 구이류 > 어패류',null,'가열하여 익히는 음식 > 굽는 음식 > 굽는 음식');
Insert into FOOD.FOOD_TBL (ID,COOKING_INSTRUCTION,INGREDIENT,MINOR_INGREDIENT,REFERENCE,COOK,COOKING_ORIGIN,FOOD_IMG,FOOD_NAME,FOOD_TYPE,INFORMATION_PROVIDER,RECIPE) values (73,'1. 갈치는 싱싱한 것으로 골라 7~8cm 길이로 토막을 내고 씻어서 2cm 간격으로 칼집을 낸다. 2. 갈치 토막에 간이 충분히 배도록 소금을 고루 뿌린다. 3. 석쇠를 달군 후 표면에 식용유를 발라 갈치 토막을 석쇠에 올린 후 앞뒤 표면이 노릇노릇해지도록 굽는다.','갈치 200g(2/3마리), 식용유 6g(1/2큰술), 소금 3g(3/4작은술)',null,null,'김동희, 서울특별시 동작구 신대방1동','왕준연, 한국요리백화 2, 범한출판사, 1985 농촌진흥청 농촌생활연구소(현 농식품자원부), 소비자가 알기 쉬운 식품영양가표, 2002','d00bd814-dfa9-44a0-b0ba-6966d9cc8295.jpg','갈치구이','부식류 > 구이류 > 구이류 > 어패류',null,'가열하여 익히는 음식 > 굽는 음식 > 굽는 음식');
Insert into FOOD.FOOD_TBL (ID,COOKING_INSTRUCTION,INGREDIENT,MINOR_INGREDIENT,REFERENCE,COOK,COOKING_ORIGIN,FOOD_IMG,FOOD_NAME,FOOD_TYPE,INFORMATION_PROVIDER,RECIPE) values (74,'1. 배추는 밑둥을 다듬고 칼집을 내어 4등분하여 15%의 굵은 소금물에 5~6시간 동안 절인 후 깨끗이 씻어 건져 물기를 뺀다. 2. 물에 찹쌀가루를 잘 풀어 찹쌀풀을 쑨 후 식으면 고춧가루를 넣어 불린다. 3. 2에 양념을 넣어 잘 섞는다. 4. 청각은 씻어 물기를 꼭 짜고 3~4cm 길이로 썬다. 5. 무는 곱게 채 썰고(5×0.2×0.2cm), 미나리, 갓은 깨끗이 다듬어 5cm 길이로 썬다. 6. 갈치는 머리를 잘라 내고 몸통을 1.5cm 간격으로 잘라 씻어 물기를 뺀다. 7. 갈치, 무, 미나리, 갓, 청각에 3을 넣고 잘 섞어 버무려 김치 속을 만든다. 8. 배춧잎 사이사이에 김치 속을 고르게 채워 넣고 쏟아지지 않도록 겉잎을 잘 싼다. 9. 항아리에 김치를 한 포기씩 차곡차곡 담아 익힌다.','배추 20kg(16포기), 갈치 1.6kg(5마리), 굵은 소금 10컵, 무 4kg(5개), 미나리 1단, 갓 1단, 청각 200g, 찹쌀가루 6큰술, 물 500mL(2 1/2컵), 고춧가루 10컵','[양념] 멸치젓 4컵, 다진 마늘 5컵, 다진 생강 2컵, 고운 소금 1컵','무와 배추를 함께 이용한 섞박지도 있다.',null,'경주시농업기술센터, 천년고도 경주 내림손맛, 2005','fa5c005e-7b6f-49f2-b168-ddfc38eeabf1.jpg','갈치김치','부식류 > 김치류 > 김치류 > 배추류',null,'가열하지 않는 음식 > 소금이나 장류에 절이는 음식 > 소금이나 장류에 절이는 음식');
Insert into FOOD.FOOD_TBL (ID,COOKING_INSTRUCTION,INGREDIENT,MINOR_INGREDIENT,REFERENCE,COOK,COOKING_ORIGIN,FOOD_IMG,FOOD_NAME,FOOD_TYPE,INFORMATION_PROVIDER,RECIPE) values (75,'1. 무는 깍둑썰어(사방 2cm) 소금에 절인 다음 씻어서 물기를 뺀다. 2. 갈치내장은 곱게 다지고, 풋고추와 붉은 고추는 씨를 빼고 송송 썬다(0.3cm). 3. 준비된 모든 재료에 양념을 넣고 버무려 항아리에 담아 숙성시킨다.','갈치내장(갈치순태) 150g, 무 850g(1개), 풋고추 30g(2개), 붉은 고추 30g(2개), 소금 1/2컵','[양념] 고춧가루 2컵, 다진 마늘 2큰술, 통깨 약간',null,null,'울산광역시농업기술센터, 울산향토음식, 2001','cebfcc8a-8e08-4d1e-aebd-35d530c72562.jpg','갈치내장김치(갈치순태김치)','부식류 > 김치류 > 김치류 > 무류',null,'가열하지 않는 음식 > 소금이나 장류에 절이는 음식 > 소금이나 장류에 절이는 음식');
Insert into FOOD.FOOD_TBL (ID,COOKING_INSTRUCTION,INGREDIENT,MINOR_INGREDIENT,REFERENCE,COOK,COOKING_ORIGIN,FOOD_IMG,FOOD_NAME,FOOD_TYPE,INFORMATION_PROVIDER,RECIPE) values (76,'1. 갈치 내장에 소금을 넣어 잘 섞는다. 2. 항아리에 넣어 밀봉해서 한 달 정도 삭힌다.','갈치내장 500g,소금 250g(2컵)',null,null,'이미애, 경상남도 고성군 상리면 자은리','문화공보부 문화재관리국, 한국민속종합조사보고서(경상남도 편), 1972 울산광역시농업기술센터, 울산향토음식, 2001','4c934d18-f03d-4c96-9fd3-f9c60671b031.jpg','갈치내장젓(갈치순태젓)','부식류 > 젓갈 및 식해류 > 젓갈 > 젓갈','손순연, 울산광역시 울주군 웅촌면 검단리','가열하지 않는 음식 > 소금이나 장류에 절이는 음식 > 소금이나 장류에 절이는 음식');
Insert into FOOD.FOOD_TBL (ID,COOKING_INSTRUCTION,INGREDIENT,MINOR_INGREDIENT,REFERENCE,COOK,COOKING_ORIGIN,FOOD_IMG,FOOD_NAME,FOOD_TYPE,INFORMATION_PROVIDER,RECIPE) values (77,'1. 무는 깨끗이 씻어 납작하게 썰어(4×5×1cm) 굵은 소금에 절인 다음 한 번 헹구어 물기를 뺀다. 2. 쪽파는 씻어 4cm 길이로 썰고, 대파는 어슷썰기 한다(0.3cm). 3. 갈치젓은 2cm 폭으로 자른다. 4. 준비된 재료에 양념을 넣고 버무려 항아리에 눌러 담는다.','무 5kg(6개),굵은 소금 1 1/2컵,갈치젓 1컵,쪽파 400g,대파 170g(5뿌리)','<양념> 고춧가루 2컵, 생강 5큰술, 멸치액젓 4큰술, 다진 마늘 2컵, 설탕, 소금 약간','갈치젓은 갈치 비늘을 긁어 내고 내장을 뺀 후 통째로 소금을 뿌려 3~4개월 삭혀서 만든다.',null,null,'blank_image.png','갈치섞박지','부식류 > 김치류 > 김치류 > 무류','이종선, 부산광역시 기장군 일광면 삼성리','가열하지 않는 음식 > 소금이나 장류에 절이는 음식 > 소금이나 장류에 절이는 음식');
Insert into FOOD.FOOD_TBL (ID,COOKING_INSTRUCTION,INGREDIENT,MINOR_INGREDIENT,REFERENCE,COOK,COOKING_ORIGIN,FOOD_IMG,FOOD_NAME,FOOD_TYPE,INFORMATION_PROVIDER,RECIPE) values (70,'1. 갈비는 찬물에 담가 핏물을 뺀 다음 뜨거운 물에 데쳐 낸다. 2. 데친 갈비에 물을 충분히 붓고 푹 끓인다. 3. 우거지는 끓는 물에 삶아 다진 양념과 된장을 넣어 무친다. 4. 2에 양념한 우거지를 넣고 국물맛이 우러날 때까지 끓인 후 소금으로 간을 맞춘다.','쇠갈비 240g, 우거지 200g, 된장 3큰술, 물 적량, 소금 약간','<다진 양념> 다진 고추 1큰술, 다진 마늘 1큰술',null,null,null,'blank_image.png','갈비탕','부식류 > 국 및 탕류 > 토장국 > 육류','최연례 전라남도 화순군 화순읍 계소리<br>','가열하여 익히는 음식 > 물을 이용한 음식 > 끓이는 음식');
Insert into FOOD.FOOD_TBL (ID,COOKING_INSTRUCTION,INGREDIENT,MINOR_INGREDIENT,REFERENCE,COOK,COOKING_ORIGIN,FOOD_IMG,FOOD_NAME,FOOD_TYPE,INFORMATION_PROVIDER,RECIPE) values (71,'1. 갈치 비늘을 긁지 않고 씻어 둔다. 2. 1에 소금을 뿌려 석쇠에 굽는다.','갈치 320g(1마리), 소금 2작은술',null,null,null,null,'blank_image.png','갈치구이','부식류 > 구이류 > 구이류 > 어패류',null,'가열하여 익히는 음식 > 굽는 음식 > 굽는 음식');
Insert into FOOD.FOOD_TBL (ID,COOKING_INSTRUCTION,INGREDIENT,MINOR_INGREDIENT,REFERENCE,COOK,COOKING_ORIGIN,FOOD_IMG,FOOD_NAME,FOOD_TYPE,INFORMATION_PROVIDER,RECIPE) values (65,'1. 갈비는 기름덩어리를 떼어 내고 7cm 정도의 너비로 토막 낸다. 2. 토막 낸 갈비에 잔 칼집을 넣은 후 참기름을 발라 재워 둔다. 3. 달군 석쇠나 팬에 2의 갈비를 넣어 앞뒤로 노릇하게 굽는다. 4. 상추는 깨끗이 씻어 물기를 빼고, 풋고추는 어슷썰며(0.3cm), 마늘은 얇게 편으로 썬다. 5. 참기름에 소금을 넣어 섞은 기름장과 상추, 풋고추, 마늘을 곁들인다.','소갈비 , 상추 , 풋고추 , 마늘 , 참기름 , 소금 적량',null,null,null,null,'blank_image.png','갈비구이(생갈비구이)','부식류 > 구이류 > 구이류 > 육류',null,'가열하여 익히는 음식 > 굽는 음식 > 굽는 음식');
Insert into FOOD.FOOD_TBL (ID,COOKING_INSTRUCTION,INGREDIENT,MINOR_INGREDIENT,REFERENCE,COOK,COOKING_ORIGIN,FOOD_IMG,FOOD_NAME,FOOD_TYPE,INFORMATION_PROVIDER,RECIPE) values (66,'1. 소갈비는 5cm 정도로 토막을 내어서 찬물에 담가 핏물을 빼고 기름기를 제거한 후 칼집을 2~3번 넣는다. 2. 냄비에 갈비가 잠길 정도의 물을 붓고 끓이다가 갈비를 넣어 살짝 익한 다음 갈비는 건져 내고 국물은 체에 밭쳐 기름기를 제거하여 깨끗하게 준비한다. 3. 양파는 적당한 크기로 썰어 놓고, 배는 강판에 갈아 분량의 재료를 넣고 양념장을 만든다. 4. 갈비와 양념장을 잘 섞어 하룻밤 정도 재워 둔다. 5. 냄비에 재워 둔 갈비와 갈비를 재워 두었던 양념장을 담고 중불에서 서서히 끓인다. 6. 갈비가 익으면 양파를 넣고 약한 불에서 서서히 익힌다.','소갈비 1kg, 양파 160g(1개), 배 190g(1/2개)','<양념장> 간장 1컵, 다진 파 4큰술, 다진 마늘 2큰술, 참기름 2작은술',null,null,null,'blank_image.png','갈비찜','부식류 > 찜 및 선류 > 찜 > 육류',null,'가열하여 익히는 음식 > 물을 이용한 음식 > 끓이는 음식');
Insert into FOOD.FOOD_TBL (ID,COOKING_INSTRUCTION,INGREDIENT,MINOR_INGREDIENT,REFERENCE,COOK,COOKING_ORIGIN,FOOD_IMG,FOOD_NAME,FOOD_TYPE,INFORMATION_PROVIDER,RECIPE) values (67,'1. 쇠갈비는 5cm 정도로 토막을 내어 찬물에 담가 핏물을 빼고 건져서 물을 넣고 삶는다. 갈비에 붙은 질긴 힘줄이나 기름 덩어리를 떼어 내고 2cm 간격으로 칼집을 넣고, 육수는 기름을 걷는다. 2. 분량의 재료로 양념을 만든다. 3. 냄비에 삶은 갈비를 담고 양념을 1/3분량을 남기고 넣어 고루 버무린 후 육수 2컵 정도를 넣어서 중간 불에서 서서히 끓이고 끓기 시작하면 약한 불에서 갈비가 무르도록 끓인다. 4. 무와 당근은 사방 3cm의 크기로 썰어 돌려 깎기하여 끓는 물에 넣어 삶아 내고, 건표고버섯은 불려서 은행잎 모양으로 썬다. 5. 갈비가 무르고 국물이 자작하게 졸면 삶은 무, 당근, 표고버섯을 넣고 남은 양념과 육수를 넣어 약한 불에서 서서히 뜸을 들인다. 6. 윤기가 나고 간이 잘 들면 밤과 은행을 넣는다. 찜 그릇에 담은 다음 달걀지단을 완자 모양이나 마름모 모양으로 썰어 고명으로 얹는다.','쇠갈비 600g, 무 300g(1/3개), 당근 200g(1 1/3개), 건표고버섯 25g(8개), 달걀 50g(1개), 밤 100g(6개), 은행 20g(10개), 물 800mL(4컵)','<양념> 간장 6큰술, 배즙 6큰술, 다진 파 2큰술, 다진 마늘 2큰술, 참기름 1큰술, 깨소금 1큰술, 후춧가루 약간',null,null,'전희정·이효지·한영실, 한국전통음식, 문화관광부, 2000','08b8a4c0-f4b5-4845-b4e2-50e6bb46687f.jpg','갈비찜(가리찜)','부식류 > 찜 및 선류 > 찜 > 육류',null,'가열하여 익히는 음식 > 물을 이용한 음식 > 수증기로 찌는 음식');
Insert into FOOD.FOOD_TBL (ID,COOKING_INSTRUCTION,INGREDIENT,MINOR_INGREDIENT,REFERENCE,COOK,COOKING_ORIGIN,FOOD_IMG,FOOD_NAME,FOOD_TYPE,INFORMATION_PROVIDER,RECIPE) values (68,'1. 갈비는 찬물에 담가 핏물을 뺀 기름덩어리를 떼어 내고 2cm 간격으로 칼집을 넣는다. 2. 당근은 깍둑썰기 하여(사방 3cm) 둥글려 깍고, 표고버섯은 은행잎 모양으로 썬다. 3. 양념장을 만들어 손질한 갈비를 2~3시간 정도 재워 둔다. 4. 솥에 넣을 때는 갈비 사이사이에 당근, 밤, 표고버섯, 은행을 넣고 약간의 물을 부어 약한 불에서 서서히 끓인다. 5. 고명으로 잣, 황백지단채를 오린다.','소갈비 800g, 당근 150g(1개), 밤(깐 것) 60g(4개), 표고버섯 50g(4개), 달걀 50g(1개), 은행 10g(5개), 잣 1작은술, 물 약간','<양념장> 간장 6큰술, 배즙 6큰술, 설탕 3큰술, 다진 파 2큰술, 다진 마늘 2큰술, 참기름 1큰술, 깨소금 1큰술, 후춧가루 1/2작은술','·갈비찜은 소갈비를 주재료로 무, 당근, 표고버섯 등의 채소를 넣고 갖은 양념을 하여 국물을 자작하게 붓고 은근한 불에서 푹 익힌 음식으로, 반상, 교자상, 주안상에 주로 올린다. 『시의전서』에는 ''''갈비를 한 치 길이로 잘라 살짝 데친 다음 양파, 곱창, 무, 다시마를 넣고 푹 삶아 건져 잘게 자르고, 표고버섯, 석이버섯도 썰고 파, 미나리는 데쳐서 갖은 양념하여 볶은 다음 그릇에 담고 고명을 얹는다''''고 기록되어 있다. ·갈비찜을 만든 다음, 석회에 양념장을 발라 가면서 구워 잣가루를 뿌려 내면 소갈비찜구이가 된다',null,'황기록, 이연채 명인의 남도 전통음식 다지리, 2000','a44048ee-879e-4d5f-94ff-9598ea44bb7b.jpg','갈비찜(가리찜)','부식류 > 찜 및 선류 > 찜 > 육류',null,'가열하여 익히는 음식 > 물을 이용한 음식 > 수증기로 찌는 음식');
Insert into FOOD.FOOD_TBL (ID,COOKING_INSTRUCTION,INGREDIENT,MINOR_INGREDIENT,REFERENCE,COOK,COOKING_ORIGIN,FOOD_IMG,FOOD_NAME,FOOD_TYPE,INFORMATION_PROVIDER,RECIPE) values (69,'1. 갈비는 4~5cm로 토막을 내어 찬물에 담가 핏물을 뺀다. 2. 두꺼운 솥에 물을 부어 끓어오르면 갈비를 넣어 끓인다. 국이 펄펄 끓어오르면 불을 약하게 줄이고 2~3시간 정도 고기가 무를 때까지 서서히 끓인다. 3. 2를 끓이는 도중에 무는 통째로 넣고, 파와 마늘은 크게 썰어서 넣고 위에 뜨는 기름과 거품은 걷어 낸다. 4. 고기와 무가 무르면 그릇에 건져 내고 국물은 식혀서 위에 뜨는 기름을 제거한다. 갈비는 먹기 좋게 잔칼집을 넣고, 무는 나박썰어(2.5×2.5×0.3cm) 양념으로 각각 고루 무친다. 5. 달걀은 흰자와 노른자를 나누어 소금을 약간 넣고 잘 풀어서 지단을 얇게 부쳐 마름모 모양(폭 2cm)으로 썬다. 6. 국물을 다시 불에 올려 끓인다가 4의 양념한 갈비와 무를 넣고 끓인다. 맛을 보아 간이 부족하면 국간장이나 소금으로 간을 맞춘다.','쇠갈비 300g, 무 200g(1/4개), 물 2.4L(12컵), 대파 25g(2/3뿌리), 통마늘 30g(1통), 달걀 50g(1개), 국간장 약간, 소금 약간','<양념> 국간장 5g(1작은술), 소금 2g(1/2작은술), 다진 파 3g(1작은술), 다진 마늘 3g(1/2작은술), 참기름 3g(1작은술), 후춧가루 약간',null,null,'정순자, 한국조리, 신광출판사, 1990 황혜성·한복려·한복진, 한국의 전통음식, 교문사, 1994 농촌진흥청 농촌생활연구소(현 농촌자원개발연구소), 소비자가 알기 쉬운 식품영양가표, 2002','e8b74c1f-f5f0-4741-adcb-556578a7b56f.JPG','갈비탕','부식류 > 국 및 탕류 > 토장국 > 육류',null,'가열하여 익히는 음식 > 물을 이용한 음식 > 끓이는 음식');
Insert into FOOD.FOOD_TBL (ID,COOKING_INSTRUCTION,INGREDIENT,MINOR_INGREDIENT,REFERENCE,COOK,COOKING_ORIGIN,FOOD_IMG,FOOD_NAME,FOOD_TYPE,INFORMATION_PROVIDER,RECIPE) values (59,'[메주 쑤기] 1. 콩을 깨끗이 씻어 물을 콩보다 훨씬 위로 올라가게 부어 끓인다. 2. 김이 나기 시작하면 불을 약하게 하여 넘어 오를 듯하면 솥 뚜껑을 닫은 채 찬물을 솥 뚜껑 위에 부어 콩이 넘지 않도록 한다. 3. 콩이 익을 때까지 약한 불에서 계속 끓이고 뜸이 들면 소쿠리에 건져 물기를 빼고, 뜨거울 때 절구에 넣어 찧은 후 네모지고 단단하게 만든다. 4. 짚을 깔고 꾸덕꾸덕하게 말린 후 짚을 십자로 해서 메주를 묶은 다음 남은 짚으로 새끼를 꼬아 따뜻한 방에 매달아 말린다. 5. 10주쯤 지난 뒤 내려서 보일러실이나 따뜻한 방에 두고 띄운다. 6. 다 띄웠으면 볕에 말려 지푸라기 붙은 것을 칼로 떼어 내고 솔로 깨끗이 털어 낸다. [간장 담그기] 7. 소금을 물에 녹여 불순물을 가라앉힌 다음 고운체에 다시 거른다. 8. 항아리는 볕을 많이 쬘 수 있는 입이 넓은 것으로 준비해서 펄펄 끓는 물을 부어 깨끗이 소독하여 씻어 낸다. 9. 항아리에 메주를 차곡차곡 쌓은 다음 그 위에 소금물을 붓고 숯을 넣고 행주로 깨끗이 닦은 고추와 대추를 넣고 뚜껑을 꼭 덮어 두었다가 열어 햇볕을 쬔 다음 항아리 가장자리를 닦고 망사로 항아리를 봉해서 40일 정도 둔다. 10. 40일 후에는 숯, 고추, 대추는 건져 내고 간장독을 준배해서 체를 올려 놓고 장을 떠서 거른다. 11. 체에 밭친 간장은 그대로 쓰기도 하고, 다려서 거품은 걷어 내고 식혀서 사용한다.','콩(대두) 14.4kg, 물 25L','[담그기] 소금 7Kg, 찹쌀 750g(4컵), 물 36L, 대추, 숯 약간','간장을 맛있게 먹으려면 볕쬐기와 통풍을 잘 조절해야 한다.',null,'강인희, 한국의 맛, 대한교과서주식회사, 1993','1a358063-ad0f-402d-a02e-555e695b3070.jpg','간장','발효식품류 > 장류 > 간장류 > 간장류',null,'가열하지 않는 음식 > 소금이나 장류에 절이는 음식 > 소금이나 장류에 절이는 음식');
Insert into FOOD.FOOD_TBL (ID,COOKING_INSTRUCTION,INGREDIENT,MINOR_INGREDIENT,REFERENCE,COOK,COOKING_ORIGIN,FOOD_IMG,FOOD_NAME,FOOD_TYPE,INFORMATION_PROVIDER,RECIPE) values (60,'1. 서촌간재미를 손질하여 6~8등분 한다. 2. 쌀뜨물에 된장을 풀어 무를 넣고 끓인다. 3. 국물이 끓으면 간재미를 넣고 고춧가루, 마늘, 양파를 넣는다. 4. 한소끔 끓여 들깨가루를 넣고 먹기 전에 대파를 송송 썰어(0.5cm) 넣는다.','간재미 1마리, 무 200g(1/4개), 양파 30g(1/4개), 쌀뜨물 1.6L(8컵), 대파 20g(1/2뿌리), 된장 2큰술, 고춧가루 1큰술, 다진마늘 1/2큰술, 들깨가루 1큰술',null,'서촌간재미는 진도 지역에서 널리 알려진 토속음식으로 겨울철에 제일 맛이 좋으며, 탕으로 끓여 먹으면 게살처럼 부드러운 맛을 느낄 수 있다.',null,'진도군농업기술센터, 고향의 맛,2003','blank_image.png','간재미탕<방법1>','부식류 > 국 및 탕류 > 곰국 및 탕 > 어패류',null,'가열하여 익히는 음식 > 물을 이용한 음식 > 끓이는 음식');
Insert into FOOD.FOOD_TBL (ID,COOKING_INSTRUCTION,INGREDIENT,MINOR_INGREDIENT,REFERENCE,COOK,COOKING_ORIGIN,FOOD_IMG,FOOD_NAME,FOOD_TYPE,INFORMATION_PROVIDER,RECIPE) values (61,'1. 간재미는 잘 씻어 두 토막 낸 후 시루에 찐다. 2. 미나리는 다듬어 5cm길이로 썬다. 3. 냄비에 멸치장국국물을 붓고 끓이다가 간재미를 넣고 미나리와 다진 붉은 고추, 다진 파와 다진 마늘을 넣어 끓인 후 소금으로 간을 맞춘다.','간재미 1마리, 미나리 100g, 멸치장국국물(멸치 · 다시마 · 물) 1.6L(8컵), 다진 붉은 고추 적량, 다진 파 적량, 다진 마늘 적량, 소금 적량',null,'서촌간재미는 진도지역에서 널리 알려진 토속음식으로 겨울철에 제일 맛이 좋으며, 탕으로 끓여 먹으면 게살처럼 부드러운 맛을 느낄 수 있다.',null,'진도군농업기술센터, 고향의 맛, 2003','blank_image.png','간재미탕<방법2>','부식류 > 국 및 탕류 > 곰국 및 탕 > 어패류','김영숙, 전라남도 진도군 지산면 민지리','가열하여 익히는 음식 > 물을 이용한 음식 > 끓이는 음식');
Insert into FOOD.FOOD_TBL (ID,COOKING_INSTRUCTION,INGREDIENT,MINOR_INGREDIENT,REFERENCE,COOK,COOKING_ORIGIN,FOOD_IMG,FOOD_NAME,FOOD_TYPE,INFORMATION_PROVIDER,RECIPE) values (62,'1. 간재미는 물에 씻지 않고 마른 면포로 등과 배등에 묻어 있는 액을 깨끗하게 닦아 낸다. 2. 간재미를 4~5토막을 내어 가로 5cm, 세로 3cm크기로 얇게 저민다. 3. 저민 간재미를 막걸리에 담가 주무른 후 막걸리를 꼭 짠다. 4. 당근은 길이대로 반을 갈라 어슷썰고(0.3cm), 대파와 풋고추도 어슷하게 썬다. 5. 그릇에 고추장, 식초, 다진 마늘, 설탕, 깨소금을 넣고 섞은 다음 간재미, 당근, 대파, 풋고추를 넣고 버무린다.','간재미 600g, 당근 100g(2/3개), 대파 35g(1뿌리), 풋고추 30g(2개), 막걸리 1컵','<초고추장 양념> 고추장 5큰술, 식초 3큰술, 다진 마늘 1 2/3큰술, 설탕 1큰술, 깨소금 1큰술','기름장에 먹을 경우에 1, 2의 과정만 거쳐 기름장에 바로 찍어 먹는다.',null,null,'1a7ec351-7d04-4d34-8e2f-47c425105bff.jpg','간재미회(간재미무침)','부식류 > 회류 > 무침 > 어패류',null,'가열하지 않는 음식 > 날것에 조미료를 곁들여 먹는 음식 > 날것에 조미료를 곁들여 먹는 음식');
Insert into FOOD.FOOD_TBL (ID,COOKING_INSTRUCTION,INGREDIENT,MINOR_INGREDIENT,REFERENCE,COOK,COOKING_ORIGIN,FOOD_IMG,FOOD_NAME,FOOD_TYPE,INFORMATION_PROVIDER,RECIPE) values (63,'1. 돼지간을 잘 삶아 식힌 뒤 0.5cm 두께로 썰어 소금과 후춧가루를 뿌린 다음 메밀가루에 고루 무친다. 2. 달걀을 풀어 소금 간을 하고 식용유를 두른 팬에 달걀물을 한 숟가락 떠 넣고 1의 간을 중앙에 얹어 지진다.','돼지간 300g, 메밀가루 3큰술, 달걀 150g(3개), 소금 1작은술, 후춧가루 1/2작은술, 식용유 적량',null,'소간을 사용하기도 하고, 메밀가루 대신 밀가루를 사용하기도 한다.',null,'제주도 농촌진흥원, 오랫동안 전하여 온 맛과 멋-제주 전통음식, 1995 제주시 농업기술센터, 제주 전통음식, 2003 제주특별자치도 농업기술원, 제주 전통음식, 2007','blank_image.png','간전','부식류 > 전류 > 전 > 육류',null,'가열하여 익히는 음식 > 기름을 이용하여 익히는 음식 > 기름을 이용하여 익히는 음식');
Insert into FOOD.FOOD_TBL (ID,COOKING_INSTRUCTION,INGREDIENT,MINOR_INGREDIENT,REFERENCE,COOK,COOKING_ORIGIN,FOOD_IMG,FOOD_NAME,FOOD_TYPE,INFORMATION_PROVIDER,RECIPE) values (64,'1. 암소갈비를 준비하여 기름기가 많은 부분은 떼에 내고 6~7cm 길이로 토막을 낸다. 2. 갈비에 붙은 고기가 떨어지지 않을 정도로 뼈 밑까지 깊고 잘게 가로 세로로 칼집을 낸다. 3. 칼집을 낸 갈비에 간장, 다진 파, 다진 마늘 설탕, 깨소금, 후춧가루를 넣고 버무린 다음 참기름을 넣고 1시간 정도 재워 둔다. 4. 양념이 잘 배었으면 중불에 올려 뼈에 붙은 힘줄이 익어서 오므라질 정도로 굽는다.','소갈비 (암소갈비) 2kg, 간장 1/2컵, 다진 파 4큰술, 다진 마늘 2큰술, 참기름 3큰술, 설탕 3큰술, 깨소금 3큰술, 후춧가루 1/3작은술',null,null,null,'광주향토음식문화연구회, 향토음식문화상품개발 상차림 선물음식, 2001','blank_image.png','갈비구이','부식류 > 구이류 > 구이류 > 육류',null,'가열하여 익히는 음식 > 굽는 음식 > 굽는 음식');
Insert into FOOD.FOOD_TBL (ID,COOKING_INSTRUCTION,INGREDIENT,MINOR_INGREDIENT,REFERENCE,COOK,COOKING_ORIGIN,FOOD_IMG,FOOD_NAME,FOOD_TYPE,INFORMATION_PROVIDER,RECIPE) values (56,'1. 쌀은 6시간 이상 물에 불려 소금을 넣고 곱게 빻아 고운체에 내린다. 설탕물을 끓여 식힌 다음 쌀가루에 뿌리면서 손으로 비벼 수분의 함량을 조절한 후 다시 체에 내린다. 손으로 쥐어 펴서 흔들어 부서지지 않을 정도면 수분량이 적당하다. 2. 꿀편에는 끓여 식힌 황설탕물에 꿀을 넣어 섞고 승검초편에는 승검초를 넣으며 만드는 방법은 백편과 같다. 3. 밤과 대추, 석이버섯은 손질하여 0.1cm 두께로 가늘게 채 썰고, 잣은 길이로 반을 잘라 비늘 잣으로 만든다. 4. 시루 밑에 기름종이를 깔고 꿀편은 2cm 두께로 안치고 고명을 얹은 후 다시 기름종이를 깔고 반복하여 승검초편과 백편을 안친다. 젖은 면포를 덮고 시루번을 붙인 후 약 30~40분 정도 찐다.','멥쌀가루 500g(3 1/3컵), 소금 1/2큰술, 꿀 80g(1/2컵), 물 1/2컵, 밤 50g(3개), 대추 30g(13개), 석이버섯 5g(5개), 잣 2큰술 멥쌀가루 500g(3 1/3컵), 소금 1/2큰술, 꿀 170g(1/2컵), 황설탕 90g(1/2컵), 물 100mL(1/2컵), 밤 50g(3개), 대추 30g(13개), 석이버섯 5g(5개), 잣 2큰술 멥쌀가루 500g(3 1/3컵), 소금 1/2큰술, 승검초가루 2큰술, 설탕 80g(1/2컵), 물 100mL(1/2컵), 밤 50g(3개), 대추 30g(13개), 석이버섯 5g(5장), 잣 2큰술','<백편> 멥쌀가루 500g(3 1/3컵), 소금 1/2큰술, 꿀 80g(1/2컵), 물 1/2컵, 밤 50g(3개), 대추 30g(13개), 석이버섯 5g(5개), 잣 2큰술 <꿀편> 멥쌀가루 500g(3 1/3컵), 소금 1/2큰술, 꿀 170g(1/2컵), 황설탕 90g(1/2컵), 물 100mL(1/2컵), 밤 50g(3개), 대추 30g(13개), 석이버섯 5g(5개), 잣 2큰술 <승검초편> 멥쌀가루 500g(3 1/3컵), 소금 1/2큰술, 승검초가루 2큰술, 설탕 80g(1/2컵), 물 100mL(1/2컵), 밤 50g(3개), 대추 30g(13개), 석이버섯 5g(5장), 잣 2큰술',null,null,'문화공보부 문화재관리국, 한국민속종합조사보고서(향토음식편), 1984 전희정·이효지·한영실, 한국전통음식, 문화관광부, 2000','485fc9a3-d420-4700-8af0-257509ff9225.jpg','각색편(백편,','떡류 > 떡류 > 찌는 떡 > 찌는 떡',null,'가열하여 익히는 음식 > 물을 이용한 음식 > 수증기로 찌는 음식');
Insert into FOOD.FOOD_TBL (ID,COOKING_INSTRUCTION,INGREDIENT,MINOR_INGREDIENT,REFERENCE,COOK,COOKING_ORIGIN,FOOD_IMG,FOOD_NAME,FOOD_TYPE,INFORMATION_PROVIDER,RECIPE) values (57,'1. 찐 흰살생선은 손으로 큼직하게 뜯는다. 2. 무는 나박썰기(3×3×0.5cm) 한다. 3. 대파와 매운 고추는 0.3cm 두께로 어슷썰기 한다. 4. 두부는 2×3×1cm 크기로 썬다. 5. 냄비에 물을 붓고 준비된 생선, 무, 다시마를 넣어 끓인다. 6. 5에 고춧가루를 풀고 두부를 넣는다. 7. 6이 끓으면 소금으로 간을 하고 대파와 매운 고추 등을 넣어 한소끔 더 끓인다.','찐 흰살생선 2마리, 두부 250g(1/2모), 무 100g, 다시마 20g(5조각), 매운 고추 60g(4개), 대파 35g(1뿌리), 고춧가루 2큰술, 소금 1작은술, 물 1.6L(8컵)',null,'·간국은 제사를 지낸 후 찐 생선을 이용하여 만든 국이다 ·갈치의 굵은 토막은 구이로 이용하고 꼬리 부분이나 가는 토막은 소금 간을 하여 간국을 끓이기도 한다.',null,'기장군농업기술센터, 기장의 향토음식, 2003','7cc2368e-10b7-406a-a9c2-c406c96ece86.jpg','간국','부식류 > 국 및 탕류 > 맑은국 > 어패류',null,'가열하여 익히는 음식 > 물을 이용한 음식 > 끓이는 음식');
Insert into FOOD.FOOD_TBL (ID,COOKING_INSTRUCTION,INGREDIENT,MINOR_INGREDIENT,REFERENCE,COOK,COOKING_ORIGIN,FOOD_IMG,FOOD_NAME,FOOD_TYPE,INFORMATION_PROVIDER,RECIPE) values (58,'1. 부아를 끓는 물에 삶는데 도중 꼬치를 찔러 가며 완전히 익도록 한다. 다 익으면 얇게 저며 소금, 후춧가루를 뿌린다. 2. 밀가루와 달걀을 씌워 팬에 식용유를 두르고 지진다. 1. 간을 0.3cm 두꼐로 저며 소금으로 주물러 씻어서 냉수에 담가 핏물을 빼어 마른 면포 위에 눌러 놓고 물기를 뺀다. 소금과 후춧가루를 조금씩 뿌린다. 2. 마른 메밀가루에 깻가루를 섞어 꼭꼭 눌러 씌워서 기름을 간 조각이 반은 잠길만큰 부어서 노릇노릇하게 바싹 지져 낸다. 천엽을 깨끗이 씻어 한 조각씩 떼어 내어 잔칼집을 내고 소금, 후춧가루를 뿌렸다가 밀가루와 달걀물을 씌워 지진다. 천엽 쪽은 칼집을 내고 가장자리도 조금씩 끓어야 오그라들지 않는다.','밀가루 15g(2큰술)','<부아전> 부아(허파) 100g, 밀가루 15g(2큰술), 달걀 50g(1개), 소금·식용유 적량, 후춧가루 약간 <간전> 간 100g, 소금 1/2작은술, 후춧가루 1/3작은술, 메밀가루 2큰술, 깨소금 1큰술, 식용유 적량 <천엽전> 천엽 100g, 밀가루 15g(2큰술), 달걀 50g(1개), 소금 1/2작은술, 후춧가루 1/3작은술, 식용유 적량','·내장은 조리하기 전 미리 손질을 잘하고 냉수로 많이 씻어야 내장 특유의 새가 없다. 부이로 꼬치를 찌르면서 삶고 천엽과 소양은 소금을 주물러 씻어 껍질을 하얗게 벗겨야 한다. 간은 메밀가루로 입혀 지지는 것이 냄새가 나지 않고 먹기 좋다. ·내장전은 큰상 차릴 때 고이는 음식에 밑받침으로 많이 쓰고 있다. 다른 전보다 무기질이 많아 권장할 만한 음식이다.',null,'문화공보부 문화재관리국, 한국민속종합조사보고서(향토음식 편), 1984','de35d237-07d4-4ce6-a50e-1dcb5c336a15.jpg','간랍(전유아,','부식류 > 전류 > 전 > 육류',null,'가열하여 익히는 음식 > 기름을 이용하여 익히는 음식 > 기름을 이용하여 익히는 음식');
Insert into FOOD.FOOD_TBL (ID,COOKING_INSTRUCTION,INGREDIENT,MINOR_INGREDIENT,REFERENCE,COOK,COOKING_ORIGIN,FOOD_IMG,FOOD_NAME,FOOD_TYPE,INFORMATION_PROVIDER,RECIPE) values (53,'1. 찹쌀을 깨끗이 씻어 1~2주일 정도 담가 둔다. 물로 여러 번 씻어 빻고 가루로 만둔 다음 체에 내린다. 2. 불린 콩에 물을 붓고 끓여 콩물을 준비해 둔다. 3. 체에 내린 찹쌀가루에 청주, 설탕, 콩물을 섞어 조금씩 넣고 주걱으로 고루 섞듯이 반죽한다. 찜솥에 젖은 면포를 깔고 반죽을 덩어리로 안쳐서 푹 찐 다음 큰 그릇에 쏟은 후 방망이로 꽈리가 일도록 힘껏 친다. 4. 안반에 쌀가루나 전분을 뿌리고 3을 펴 놓아 밀대로 0.4cm 두께로 민다. 약간 굳힌 다음 가로 2.5cm, 세로 3cm 크기로 썬다. 5. 채반 위에 한지를 깔고 수분 함량이 20% 정도가 되도록(갈라지지 않을 때까지) 말린 다. 6. 낮은 온도의 식용유에 5~10분 정도 담가서 불린 다음 130~150℃의 온도의 식용유에 째빨리 옮겨 넣고 반 정도 부풀어 오르면 뒤집어서 네 귀를 눌러 모양을 반듯하게 만들고 완전히 부풀어 오르면 건져서 기름을 빼 놓는다. 7. 튀겨낸 산자에 즙청액을 바르고, 승검초가루, 송홧가루, 통깨, 계핏가루, 세반을 고물로 묻혀 낸다.','찹쌀 900g(5컵), 청주 3큰술, 설탕 3큰술, 식용유 적량','<콩물> 불린 콩 1/2컵, 물 100mL(1/2컵) <즙청액> 설탕 1/2큰술, 물엿 290g(1컵), 꿀 1큰술 <고물> 승검초가루 1/2컵, 송홧가루 1/2컵, 계핏가루 1/2컵, 통깨 45g(1/2컵), 세반 1컵','·유과는 예부터 내려 오는 우리 고유의 과자로 기름에 지져서 만들기 때문에‘기름 유(油)’자가 붙었다. 유과는 여름철에는 덥고 습기가 많아서 바탕이 쉽게 눅고 엿이 늘어져서 만들기가 어려웠기 때문에 겨울철, 특히 설을 앞두고 많이 만들어 먹었다고 한다. 유과는 크기나 모양이 다양하며 쓰임새도 많다고 한다. ·골마지란 간장, 된장, 술, 초, 김치 따위의 물기 많은 음식물 겉면에 생기는 곰팡이 같은 물질로 연한 노란색을 띤다.',null,'부안군농업기술센터, 부안 향토음식, 2001 네이버사전(두산백과), www.100naver.com/, 2006','af6b901c-44f5-4dbd-a84e-f0e448f13fc5.jpg','각색산자','다과류 > 과정류 > 유밀과 > 유밀과',null,'가열하여 익히는 음식 > 기름을 이용하여 익히는 음식 > 기름을 이용하여 익히는 음식');
Insert into FOOD.FOOD_TBL (ID,COOKING_INSTRUCTION,INGREDIENT,MINOR_INGREDIENT,REFERENCE,COOK,COOKING_ORIGIN,FOOD_IMG,FOOD_NAME,FOOD_TYPE,INFORMATION_PROVIDER,RECIPE) values (54,'1. 쇠고기는 결대로 굵게 채썰어 (5×0.3×0.3cm) 양념장으로 무친다. 2. 건표고버섯은 물에 불려 기둥을 떼고 0.3cm 굵기로 채 썰어 간장과 참기름으로 무친다. 3. 숙주는 머리와 꼬리를 떼고 끓는 물에 살짝 데쳐 소금과 참기름에 무친다. 4. 당근과 무는 납작하게 채 썰어 (5×0.5×0.2cm) 끓는 물에 살짝 데쳐 소금과 참기름으로 무친다. 5. 실파도 5cm 길이로 자른다. 6. 전골 냄비에 각색 재료를 보기 좋게 담고 육수에 간을 맞추어 붓고 끓인다. 7. 달걀은 풀어서 익은 전골음식을 찍어 먹거나 통째 끓는 장국에 넣어 반숙하여 먹는다.','쇠고기(등심이나 안심) 300g, 표고버섯 15g(5개), 숙주 100g, 당근 50g(1/3개), 무 100g, 실파 100g, 달걀 50g(1개), 육수 400mL(2컵), 간장 적량, 소금 적량, 참기름 적량','<고기 양념> 간장 3큰술, 설탕 1 1/2큰술, 다진 파 2큰술, 다진 마늘 1큰술, 깨소금 2큰술, 참기름 1큰술, 후춧가루 1작은술','·내장(양, 천엽, 간, 염통, 콩팥)을 섞어 넣을 수도 있으며, 버섯류를 많이 넣어도 좋다. 전골의 다양한 재료를 손쉽게 즉석에서 만들어 먹을 수 있고, 반상이나 주안상에 반드시 따라 가는 음식이었다. 재료들을 곁상에 준비하고 화로와 전골냄비를 들고 들어가 곁에서 조리하면서 대접한다. ·전골은 여러 가지 재료를 전골 냄비에 넣고 간장으로 간을 한 육수를 부어 끓이는 음식을 말하는데, 한국음식에는 고유한 신선로가 있다. 신선로를 간단하게 만든 것이 바로 전골냄비이다. 여러 가지 재료를 전으로 만들어 넣거나 그냥 빛깔을 보기 좋게 맞춰 넣고 간장으로 간을 한 맑은 육수로 끓인 것이 전골이다. 전골이라는 말은 아주 옛날 우리나라 군사들이 전쟁터에서 조리 기구나 그릇이 없자 철로 만들어 머리를 썻던 전립을 벗어 거기다 여러 가지 재료를 넣고 음식을 끓여 먹었던 데서 연유한 것이라는 이야기도 있다.',null,'문화공보부 문화재관리국, 한국민속종합조사보고서(향토음식편), 1984','2676ed6d-4330-4408-93a7-94bbf8e9e5c5.jpg','각색전골','부식류 > 구이류 > 구이류 > 육류',null,'가열하여 익히는 음식 > 물을 이용한 음식 > 끓이는 음식');
Insert into FOOD.FOOD_TBL (ID,COOKING_INSTRUCTION,INGREDIENT,MINOR_INGREDIENT,REFERENCE,COOK,COOKING_ORIGIN,FOOD_IMG,FOOD_NAME,FOOD_TYPE,INFORMATION_PROVIDER,RECIPE) values (55,'1. 도라지, 연근, 우엉은 껍질을 벗기고 연근은 0.5cm 두께로 썬다. 2. 끓는 물에 소금을 약간 넣고 1을 데친 후 채반에 담아 물기를 빼고 꾸덕꾸덕하게 말린다. 3. 냄비에 물과 물엿을 넣어 잘 섞은 후 2와 잣을 넣고 약한 불에 조린다. 4. 3이 걸쭉해지면 꿀을 넣어 잘 섞고 더 조린다.','도라지 100g(대 5뿌리), 연근 100g(2/3개), 잣 3큰술, 물 200ml(1컵), 물엿 1컵, 꿀 3큰술, 소금 약간, 우엉 100g(2/3개)',null,'사과, 무, 오이로도 정과를 만든다.',null,'문화공보부 문화재관리국, 한국민속종합조사보고서(향토음식편), 1984 농촌진흥청 농촌영양개선연수원(현 농촌자원개발연구소), 한국의 향토음식, 1994 성주군농업기술센터, 성주 향토음식의 맥, 2004 경주시농업기술센터, 천년고도 경주 내림손맛, 2005 대구광역시, 대구 전통향토음식, 2005','blank_image.png','각색정과(도라지정과,','다과류 > 과정류 > 정과 > 정과',null,'가열하여 익히는 음식 > 물을 이용한 음식 > 약간의 수분을 양념과함께 넣고 익혀 양념이 식품에 스며들게 하는 음식');
Insert into FOOD.FOOD_TBL (ID,COOKING_INSTRUCTION,INGREDIENT,MINOR_INGREDIENT,REFERENCE,COOK,COOKING_ORIGIN,FOOD_IMG,FOOD_NAME,FOOD_TYPE,INFORMATION_PROVIDER,RECIPE) values (46,'1. 가지는 되도록 작은 것으로 골라서 오이소박이 담듯이 양끝을 붙인 채 가운데에 칼집을 넣어 소금을 약간 넣은 끓는 물에 살짝 데쳐 내어 채반에 건져서 면포에 차곡차곡 싸서 무거운 것으로 눌러 물기를 빼고 항아리나 병에 담는다. 2. 마늘과 생강은 납작하게 저미고, 마른 고추는 씨를 빼고 어슷하게 썰어 냄비에 간장, 식초, 설탕물을 끓여서 식혀 1의 항아리에 붓고 떠오르지 않게 위를 돌이나 접시로 눌러 둔다. 3. 4일 후에 다시 간장물을 쏟아 내고 끓여 식혀서 붓고, 5일 후에 마찬가지로 끓여 붓는다. 졸아들어 지나치게 짜면 물을 조금 넣어 끓인다. 4. 상에 낼 때는 폭 1cm 정도로 썰어서 참기름, 설탕, 깨소금으로 무친다.','가지 1kg(소 10개), 소금 약간','<양념> 간장 460g(2컵), 식초 70g(5큰술), 설탕 60g(5큰술), 마늘 20g(5쪽), 생강 10g(2쪽), 마른 고추 10g(2개)',null,null,'정순자, 한국조리, 신광출판사, 1990 강인희, 한국의 맛, 대한교과서주식회사, 1993 황혜성·한복려·한복진, 한국의 전통음식, 교문사, 1994','blank_image.png','가지장아찌','부식류 > 장아찌류 > 장아찌류 > 소금물에 담근 것',null,'무치는 음식 > 생으로 무치는 음식 > 생으로 무치는 음식');
Insert into FOOD.FOOD_TBL (ID,COOKING_INSTRUCTION,INGREDIENT,MINOR_INGREDIENT,REFERENCE,COOK,COOKING_ORIGIN,FOOD_IMG,FOOD_NAME,FOOD_TYPE,INFORMATION_PROVIDER,RECIPE) values (47,'1. 가지는 다듬어 깨끗이 씻어서 물기를 뺀 다음 끓여 식힌 소금물에 2일 정도 담가 두었다가 건져 물기를 빼서 꼬들꼬들하게 말려 놓는다. 2. 간장과 국간장을 달인 다음 식힌다. 3. 1의 가지를 항아리에 담고 식힌 양념장을 부어 돌로 눌러 놓은 다음 양념장을 따라 내어 식히기를 3~4회 반복한다.','가지 4kg(30개), 설탕 2컵, 물엿 3컵, 굵은 소금 1큰술','[소금물] 소금 5컵, 물 4L(20컵) [양념장] 간장 2 1/2컵, 국간장 2 1/2컵','가을 가지로 담아야 맛이 더 좋다.',null,'제주특별자치도 농업기술원, 제주 전통음식, 2007','blank_image.png','가지장아찌(가지지)','부식류 > 장아찌류 > 장아찌류 > 간장에 담근 것',null,'가열하지 않는 음식 > 소금이나 장류에 절이는 음식 > 소금이나 장류에 절이는 음식');
Insert into FOOD.FOOD_TBL (ID,COOKING_INSTRUCTION,INGREDIENT,MINOR_INGREDIENT,REFERENCE,COOK,COOKING_ORIGIN,FOOD_IMG,FOOD_NAME,FOOD_TYPE,INFORMATION_PROVIDER,RECIPE) values (48,'1. 밀가루에 고추장과 물을 넣어서 잘 풀어 준다. 2. 가지는 반으로 잘라 0.5cm 두께로 납작하게 썰고, 풋고추는 길이대로 반으로 가른다. 3. 가지와 고추를 번갈아가면 꼬치에 끼운다. 4. 가지꼬치에 밀가루 반죽을 묻히고, 가열한 팬에 식용유를 둘러 앞뒤로 노릇하게 지진다.','가지 360g(3개), 풋고추 100g(6개), 밀가루 110g(1컵), 물 100mL(1/2컵), 고추장 1큰술, 식용유 1큰술',null,'별도의 소금 간을 하지 않고 고추장의 간을 이용한다.',null,null,'7dec16c9-81ec-4def-bcc9-ca496f1fd264.jpg','가지적','부식류 > 전류 > 누름적(산적) > 채소류','최윤자, 경상북도 성주군','가열하여 익히는 음식 > 기름을 이용하여 익히는 음식 > 기름을 이용하여 익히는 음식');
Insert into FOOD.FOOD_TBL (ID,COOKING_INSTRUCTION,INGREDIENT,MINOR_INGREDIENT,REFERENCE,COOK,COOKING_ORIGIN,FOOD_IMG,FOOD_NAME,FOOD_TYPE,INFORMATION_PROVIDER,RECIPE) values (49,'1. 가지는 껍질을 벗겨 1cm 두께로 어슷하게 썰어 찬물에 담가 두었다가 물기를 뺀다. 2. 가지에 소금을 살짝 뿌려 간을 하고 밀가루를 묻혀 달걀물에 담갔다가 팬에 노릇하게 지진다.','가지 120g(1개), 달걀 50g(1개), 밀가루 25g(3큰술), 소금 적량, 식용유 적량',null,null,null,'전희정·이효지·한영실, 한국전통음식, 문화관광부,2000','e283937e-773e-4602-af68-ab378d95be98.jpg','가지전','부식류 > 전류 > 전 > 채소류',null,'가열하여 익히는 음식 > 기름을 이용하여 익히는 음식 > 기름을 이용하여 익히는 음식');
Insert into FOOD.FOOD_TBL (ID,COOKING_INSTRUCTION,INGREDIENT,MINOR_INGREDIENT,REFERENCE,COOK,COOKING_ORIGIN,FOOD_IMG,FOOD_NAME,FOOD_TYPE,INFORMATION_PROVIDER,RECIPE) values (50,'1. 가지는 꼭지를 떼어 내고 깨끗이 씻어서 얇게 길이로 얇게 썬 후 소금으로 뿌려 간을 한다.. 2. 밀가루와 물, 소금을 섞어 반죽을 한다. 3. 가지의 수분을 마른 면포로 닦아 내고 밀가루를 고루 묻힌 후 밀가루 반죽을 씌운다. 4. 팬에 식용유를 두르고 4의 가지를 올린 다음 뜨거워지면 불을 줄이고 타지 않도록 앞뒤로 뒤집어가면서 노릇노릇하게 지진다.','가지 360g(3개), 밀가루 2큰술, 물 2큰술, 소금 2작은술, 식용유 적량',null,null,null,'광양시농업기술센터 광양시생활개선회, 광양향토음식, 2001','blank_image.png','가지전','부식류 > 전류 > 전 > 채소류','허남희, 전라남도 광양시 봉강면 봉당리<br>','가열하여 익히는 음식 > 기름을 이용하여 익히는 음식 > 기름을 이용하여 익히는 음식');
Insert into FOOD.FOOD_TBL (ID,COOKING_INSTRUCTION,INGREDIENT,MINOR_INGREDIENT,REFERENCE,COOK,COOKING_ORIGIN,FOOD_IMG,FOOD_NAME,FOOD_TYPE,INFORMATION_PROVIDER,RECIPE) values (51,'1. 가지는 연한 것을 골라 8cm 길이로 토막을 내고 길이로 세 군데 칼집을 넣어 소금물에 약간 절여 물기를 제거한다. 2. 쇠고기를 곱게 다져 분량의 양념과 짧게 끊은 실고추를 섞어 소를 만들고 절여 놓은 가지 속에 놓는다. 3. 달걀은 황백으로 지단을 부쳐 마름모 썬다(폭 2cm). 4. 냄비 밑에 파잎을 굵게 썰어 깔고 그 위에 소를 넣은 가지를 담은 후 육수국물을 자작하게 부어 끓인다. 5. 그릇에 담아낼 때 황백지단을 얹어 낸다.','가지 240g(2개), 쇠고기 100g, 대파 35g(1뿌리), 달걀 50g(1개), 육수 (양지머리) 1컵','<양념> 소금 1작은술, 실고추 3g, 고추장 2작은술, 간장 2작은술, 다진 파 2작은술, 다진 마늘 1작은술, 설탕 1작은술, 참기름 2작은술, 깨소금 2작은술, 후춧가루 약간',null,null,'전희정·이효지·한영실, 한국전통음식, 문화관광부, 2000','blank_image.png','가지찜','부식류 > 찜 및 선류 > 찜 > 채소류',null,'가열하여 익히는 음식 > 물을 이용한 음식 > 수증기로 찌는 음식');
Insert into FOOD.FOOD_TBL (ID,COOKING_INSTRUCTION,INGREDIENT,MINOR_INGREDIENT,REFERENCE,COOK,COOKING_ORIGIN,FOOD_IMG,FOOD_NAME,FOOD_TYPE,INFORMATION_PROVIDER,RECIPE) values (52,'1. 송화가루에 꿀과 된 조청을 넣고 반죽한다. 2. 다식판에 참기름을 바르거나 비닐을 깐다. 3. 반죽을 알맞게 떼 내어 다식판에 넣고 엄지손가락으로 꼭꼭 눌러 모양이 나게 박아낸다.','송화가루 180g(2컵), 꿀 1큰술, 된 조청 2큰술, 참기름 약간',null,'송화는 봄에 소나무에 피는 것으로 가루를 털어서 물을 부어 우려서 말려 둔 것을 꿀을 넣고 반죽하여 다식판에 박는다. 일년 중 4-5월 사이에 20여일 밖에 채취하지 못하므로 귀하며 예로부터 중풍, 혈액순환, 노화방지, 피부미용에 좋은 효과가 있는 것으로 알려져 있다. 몸을 가볍게 하고 정신을 맑게 해주며 감기 예방의 효과도 있다.','안갑승, 경기도 가평군 가평읍 대곡리','문화공보부 문화재관리국, 한국민속종합조사보고서(향토음식편), 1984 경기도 농촌진흥원, 경기향토요리, 1991 이승교, 경기지역향토음식조사, 수원대학교논문집10권, 1992','blank_image.png','가평송화다식','다과류 > 과정류 > 다식 > 다식',null,'가열하여 익히는 음식 > 물을 이용한 음식 > 수증기로 찌는 음식');
Insert into FOOD.FOOD_TBL (ID,COOKING_INSTRUCTION,INGREDIENT,MINOR_INGREDIENT,REFERENCE,COOK,COOKING_ORIGIN,FOOD_IMG,FOOD_NAME,FOOD_TYPE,INFORMATION_PROVIDER,RECIPE) values (40,'1. 조갯살은 깨끗하게 씻는다. 2. 가지는 반으로 갈라 큼직하게 썰고, 부추는 5cm 길이로 자른다. 3. 느타리버섯은 길이대로 찢고, 풋고추는 어슷썰기 한다(0.3cm). 4, 냄비에 물(5 1/2컵)을 붓고 조갯살, 가지, 부추, 풋고추, 다진 마늘을 넣어 끓인 후 물(1/2컵)에 밀가루(또는 찹쌀가루)를 풀어서 넣는다. 5. 끓으면 국간장으로 간을 하고 방아잎을 넣는다.','가지 240g(2개), 조갯살 140g(2/3컵), 느타리버섯 50g(3개), 부추 30g, 풋고추 30g(2개), 방아잎 30g, 밀가루 (또는 찹쌀가루) 110g(1컵), 물 1.2L(6컵), 국간장 1/3큰술, 다진 마늘 1작은술',null,'방아잎은 주로 해안 지방에서 생선음식의 비린내를 제거하기 위해 이용되는 향신료이다',null,'김태정, 쉽게 찾는 우리나물, 현암사, 1998','blank_image.png','가지가루찜(가지가루찜국)','부식류 > 국 및 탕류 > 맑은국 > 채소류',null,'가열하여 익히는 음식 > 물을 이용한 음식 > 수증기로 찌는 음식');
Insert into FOOD.FOOD_TBL (ID,COOKING_INSTRUCTION,INGREDIENT,MINOR_INGREDIENT,REFERENCE,COOK,COOKING_ORIGIN,FOOD_IMG,FOOD_NAME,FOOD_TYPE,INFORMATION_PROVIDER,RECIPE) values (41,'1. 가지는 꼭지를 떼고 6~7cm길이로 썬 다음 가운데에 칼집을 여러 개 넣어 소금물에 절여 둔다. 2. 절여진 가지는 물에 헹궈서 면포에 싸고 무거운 것으로 눌러 놓아 물기를 뺀다. 3. 쪽파는 다듬어 깨끗이 씻은 다음 송 송썬다(0.3cm). 4. 넓은 그릇에 쪽파, 새우젓국, 고춧가루, 다진 마늘, 다진 생강, 소금을 넣고 섞어서 양념을 만들어 놓는다. 5. 2에서 준비한 가지의 칼집 사이에 양념을 넣어서 숙성시킨다.','가지 1kg(10개), 쪽파 100g, 새우젓국 80g(1/3컵), 고춧가루 40g(1/2컵), 다진 마늘 2큰술, 다진 생강 1큰술, 소금 1작은술',null,'·가지는 가늘고 작고 곧으며 윤기가 나는 것을 고른다. ·새우젓국은 새우젓을 다지거나 또는 냄비에 담아 물, 소금을 넣고 끓인 다음 체에 밭쳐 만든다.',null,'전라북도 농촌진흥원, 전북의 맛, 1988','9aec72df-3e30-4fc7-94da-11411a550b39.jpg','가지김치','부식류 > 김치류 > 김치류 > 과채류',null,'가열하지 않는 음식 > 소금이나 장류에 절이는 음식 > 소금이나 장류에 절이는 음식');
Insert into FOOD.FOOD_TBL (ID,COOKING_INSTRUCTION,INGREDIENT,MINOR_INGREDIENT,REFERENCE,COOK,COOKING_ORIGIN,FOOD_IMG,FOOD_NAME,FOOD_TYPE,INFORMATION_PROVIDER,RECIPE) values (42,'1. 가지를 통째로 끓는 물에 넣어 살짝 데쳐 하루 정도 햇볕에 말린 후 오이소박이처럼 칼집을 낸다. 2. 다진 파, 다진 마늘, 실고추 소금을 섞어 양념을 만들고 가지 속에 채워 넣는다. 3. 항아리에 담고 간장을 부어 익힌다.','가지 적량, 간장 적량','[양념] 소금, 다진 파, 다진 마늘, 실고추 적량','·가을 가지는 단맛이 나서 더욱 좋다. ·늦가을에 담가 겨울까지 두고 먹는 것으로 간장국물을 따라 내어 끓여 식혀서 붓기를 세 번 정도 하면 변질되지 않고 먹을 수 있다.',null,'한국관광공사, 한국의 전통음식, www.tourkorea.or.kr/, 2006 문화공보부 문화재관리국, 한국민속종합조사보고서(향토음식 편), 1984','822d3ced-5761-4514-b397-910134da1a51.jpg','가지김치','부식류 > 김치류 > 김치류 > 과채류',null,'가열하지 않는 음식 > 소금이나 장류에 절이는 음식 > 소금이나 장류에 절이는 음식');
Insert into FOOD.FOOD_TBL (ID,COOKING_INSTRUCTION,INGREDIENT,MINOR_INGREDIENT,REFERENCE,COOK,COOKING_ORIGIN,FOOD_IMG,FOOD_NAME,FOOD_TYPE,INFORMATION_PROVIDER,RECIPE) values (43,'1. 가지는 꼭지 부분을 떼어내고 2등분 한 다음 밥을 뜸 들일 때 가지를 얹어 찌거나 찜통에 넣어 쪄서 식힌다. 2. 식힌 가지는 손으로 가늘게 찢어 간장, 다진 마늘, 다진 파, 참기름, 깨소금을 넣어 양념한다.','가지 360g(3개)','[양념] 간장 2큰술, 다진 마늘 2작은술, 다진 파 4작은술, 참기름 1큰술, 깨소금 2작은술',null,null,'제주도 농촌진흥원, 오랫동안 전하여 온 맛과 멋-제주 전통음식, 1995 제주특별자치도 농업기술원, 제주 전통음식, 2007','b987a130-8916-4e5d-ae24-eb5ae1b08f3e.jpg','가지나물','부식류 > 나물류 > 숙채 > 숙채',null,'무치는 음식 > 익혀서 무치는 음식 > 익혀서 무치는 음식');
Insert into FOOD.FOOD_TBL (ID,COOKING_INSTRUCTION,INGREDIENT,MINOR_INGREDIENT,REFERENCE,COOK,COOKING_ORIGIN,FOOD_IMG,FOOD_NAME,FOOD_TYPE,INFORMATION_PROVIDER,RECIPE) values (44,'1. 가지는 깨끗이 씻어 밥솥이나 찜통이나 찐 다음 길이로 5~6등분 갈라 놓는다. 2. 분량의 양념으로 양념장을 만든다. 3. 가지에 양념장을 넣고 잘 무친 후 소금으로 간을 맞춘다.','가지 240g(2개), 소금 3g(1작은술)','[양념장] 간장 8g(1/2큰술), 다진 파6g(2/3큰술), 다진 마늘6g(1작은술),참기름 2g(2/3작은술),깨소금 1g(1/4작은술)',null,null,'강인희, 한국의 맛, 대한교과서주식회사, 1993 농촌진흥청 농촌생활연구소(현 농촌자원개발연구소), 소비자가 알기 쉬운 식품영양가표, 2002 재치영양사,www.yori.co.kr/, 2006','blank_image.png','가지나물','부식류 > 나물류 > 숙채 > 숙채',null,'무치는 음식 > 익혀서 무치는 음식 > 익혀서 무치는 음식');
Insert into FOOD.FOOD_TBL (ID,COOKING_INSTRUCTION,INGREDIENT,MINOR_INGREDIENT,REFERENCE,COOK,COOKING_ORIGIN,FOOD_IMG,FOOD_NAME,FOOD_TYPE,INFORMATION_PROVIDER,RECIPE) values (45,'1. 가지는 가늘고 연한 것으로 골라 6cm 정도로 토막을 내어 양끝을 1cm 씩 남기고 오이소박이처럼 칼집을 세 번씩 넣어 연한 소금물에 담갔다가 살짝 데친다. 2. 쇠고기는 살로 곱게 다지고 건표고버섯은 불려서 0.2cm 너비로 곱게 채 썰어 합하여 고기 양념으로 고루 무친다. 3. 가지를 마른 면보로 물기를 닦고 칼집의 사이에 양념한 쇠고기를 채워 넣는다. 4. 달걀은 황백으로 나누어 지단을 부쳐 곱게 채 썬다(5×0.2×0.2cm). 5. 냄비에 간장과 설탕, 육수를 붓고 불에 올려 끓어오르면 소를 채운 가지를 나란히 놓고 끓인다. 도중에 불을 줄이고 가끔 국물을 끼얹어서 고루 간이 들도록 한다. 6. 가지가 연하게 익고 국물이 거의 없어지면 그릇에 담고 황백지단채와 실고추, 석이버섯채를 얹는다.','가지(中) 240g(2개), 쇠고기 150g, 실고추 적량, 석이버섯채 적량, 설탕 1작은술, 달걀 50g(1개), 간장 4큰술, 건표고버섯 6g(2개), 육수 200mL(1컵)','<고기 양념> 간장 2큰술, 설탕 1큰술, 다진 파 4작은술, 다진 마늘 2작은술, 참기름 2작은술, 깨소금 2작은술, 후춧가루 약간',null,null,'전희정·이효지·한영실, 한국전통음식, 문화관광부, 2000','b854fb0e-0ecf-44ae-bbf2-ace27089cb09.jpg','가지선','부식류 > 찜 및 선류 > 선 > 채소류',null,'가열하여 익히는 음식 > 물을 이용한 음식 > 끓이는 음식');
Insert into FOOD.FOOD_TBL (ID,COOKING_INSTRUCTION,INGREDIENT,MINOR_INGREDIENT,REFERENCE,COOK,COOKING_ORIGIN,FOOD_IMG,FOOD_NAME,FOOD_TYPE,INFORMATION_PROVIDER,RECIPE) values (31,'1. 가죽잎을 물에 씻은 다음 끓는 물에 살짝 데쳐서 햇볕에 잘 말린다. 2. 1의 말린 가죽잎을 식용유에 살짝 볶음 다음 양념을 넣어 잘 섞어 주며 볶는다.','가죽잎 300g, 식용유 1큰술','<양념> 국간장 2큰술, 통깨 1큰술, 참기름 1작은술, 다진 마늘 약간, 소금 약간, 설탕 약간',null,null,'전라남도 농총진흥원, 향토요리모음, 1979 적문, 누구나 손쉽게 만들 수 있는 전통사찰음식, 우리출판사, 2000','blank_image.png','가죽잎볶음','부식류 > 나물류 > 숙채 > 숙채','박석희, 전라남도 나주군 나주읍 송월리','가열하여 익히는 음식 > 물을 이용한 음식 > 끓이는 음식');
Insert into FOOD.FOOD_TBL (ID,COOKING_INSTRUCTION,INGREDIENT,MINOR_INGREDIENT,REFERENCE,COOK,COOKING_ORIGIN,FOOD_IMG,FOOD_NAME,FOOD_TYPE,INFORMATION_PROVIDER,RECIPE) values (32,'1. 가죽잎은 부드러운 것으로 골라 살짝 데쳐 찬물에 헹구어 꾸덕꾸덕하게 말린다. 2. 물에 찹쌀가루를 풀어 찹쌀풀을 되직하게 끓여 양념장을 넣고 골고루 섞는다. 3. 말린 가죽잎에 2의 찹쌀풀을 도톰하게 발라 채반에 펴 말리다가 꾸덕꾸덕해지면 줄에 매달아 말린다. 4. 석쇠에 구워 먹거나 식용유에 튀겨 먹는다.','가죽잎 400g, 찹쌀가루 300g(3컵), 물 적량','<양념장> 고추장 3큰술, 다진 마늘 1작은술, 통깨 2큰술, 참기름 2작은술, 간장 1큰술',null,null,'광주군향토음식연구회, 너른고을 향토음식, 1997','blank_image.png','가죽잎부각','부식류 > 마른찬류 > 부각 > 채소류',null,'가열하여 익히는 음식 > 기름을 이용하여 익히는 음식 > 기름을 이용하여 익히는 음식');
Insert into FOOD.FOOD_TBL (ID,COOKING_INSTRUCTION,INGREDIENT,MINOR_INGREDIENT,REFERENCE,COOK,COOKING_ORIGIN,FOOD_IMG,FOOD_NAME,FOOD_TYPE,INFORMATION_PROVIDER,RECIPE) values (33,'1. 연한 가죽잎을 골라 끓는 물에 살짝 데쳐서 찬물에 헹구고 채반에 널어 꾸덕꾸덕하게 말린다. 2. 찹쌀가루에 물을 부어 찹쌀풀을 되직하게 쑨 다음 양념을 넣고 고루 섞어 식힌다. 3. 2의 찹쌀풀을 가죽잎 3장을 한 데 모아 겉면에 고루 발라서 채반에 펴 널어 통풍이 잘 되는 곳에서 말린다. 4. 먹을 때는 석쇠에 굽거나 기름에 튀겨 낸다.','가죽 잎 20장, 찹쌀가루 50g(1/2컵), 물 200mL(1컵), 식용유 적량','[양념] 고추장 2큰술, 간장 1작은술, 다진 마늘 1큰술, 통깨 1큰술, 참기름 1작은술','가죽잎에 찹쌀풀을 바른 뒤 마른 찹쌀가루를 뿌려 주면 체반에 달라붙지 않고 건조도 빠르기 때문에 깨끗하게 말릴 수 있다.',null,null,'blank_image.png','가죽잎부각','부식류 > 마른찬류 > 부각 > 채소류',null,'가열하여 익히는 음식 > 기름을 이용하여 익히는 음식 > 기름을 이용하여 익히는 음식');
Insert into FOOD.FOOD_TBL (ID,COOKING_INSTRUCTION,INGREDIENT,MINOR_INGREDIENT,REFERENCE,COOK,COOKING_ORIGIN,FOOD_IMG,FOOD_NAME,FOOD_TYPE,INFORMATION_PROVIDER,RECIPE) values (34,'1. 가죽잎은 씻어 물기를 빼고 잘게 자른다. 2. 밀가루에 소금, 물, 달걀을 넣고 반죽한 후 가죽잎을 넣고 섞는다. 3. 달군 팬에 식용유를 두르고 2를 한 국자씩 떠 넣어 앞뒤로 노릇하게 지진다.','밀가루 220g(2컵), 가죽잎 200g, 달걀 50g(1개), 물 250mL(1 1/4컵), 소금 1작은술, 식용유 1큰술',null,null,null,'농촌진흥청, 향토음식, www2.rda.go.kr/food/, 2006','blank_image.png','가죽잎전','부식류 > 전류 > 전 > 채소류','김희석, 경상남도 거창군 원상동<br>','가열하여 익히는 음식 > 기름을 이용하여 익히는 음식 > 기름을 이용하여 익히는 음식');
Insert into FOOD.FOOD_TBL (ID,COOKING_INSTRUCTION,INGREDIENT,MINOR_INGREDIENT,REFERENCE,COOK,COOKING_ORIGIN,FOOD_IMG,FOOD_NAME,FOOD_TYPE,INFORMATION_PROVIDER,RECIPE) values (35,'1. 가죽잎은 씻어서 끓는 물에 데친 다음 찬물에 헹궈 물기를 제거한 후 적당한 크기로 썬다. 2. 고추장, 식초, 물엿, 깨소금, 다진 파, 다진 마늘, 소금을 섞어 양념을 만든다. 3. 가죽잎에 양념을 넣고 버무린다.','가죽잎 300g, 참기름 약간','[양념] 고추장 2큰술, 식초 1큰술, 물엿 1큰술, 깨소금 1큰술, 다진 파 1작은술, 다진 마늘 1작은술, 소금 약간','가죽잎은 향기가 날 정도의 어린 순을 송이째 딴다.',null,null,'blank_image.png','가죽잎초무침','부식류 > 나물류 > 숙채 > 숙채',null,'무치는 음식 > 익혀서 무치는 음식 > 익혀서 무치는 음식');
Insert into FOOD.FOOD_TBL (ID,COOKING_INSTRUCTION,INGREDIENT,MINOR_INGREDIENT,REFERENCE,COOK,COOKING_ORIGIN,FOOD_IMG,FOOD_NAME,FOOD_TYPE,INFORMATION_PROVIDER,RECIPE) values (36,'1. 가죽잎은 깨끗이 씻어 물기를 뺀다. 2. 밀가루에 고추장과 물을 섞어 반죽한다. 3. 1의 가죽잎에 밀가루 반죽을 묻혀 달군 팬에 식용유를 두르고 지져 낸다.','가죽잎 10장, 밀가루 220g(2컵), 고추장 2큰술, 물 400mL(2컵), 소금 1작은술, 식용유 적량',null,null,null,null,'92a42241-665f-4fcb-ae23-bf906279bdb4.jpg','가죽장떡(참죽장떡)','부식류 > 전류 > 전 > 채소류',null,'가열하여 익히는 음식 > 기름을 이용하여 익히는 음식 > 기름을 이용하여 익히는 음식');
Insert into FOOD.FOOD_TBL (ID,COOKING_INSTRUCTION,INGREDIENT,MINOR_INGREDIENT,REFERENCE,COOK,COOKING_ORIGIN,FOOD_IMG,FOOD_NAME,FOOD_TYPE,INFORMATION_PROVIDER,RECIPE) values (37,'1. 가죽잎은 소금물에 2~3일 정도 절여 물기를 꼭 짠다. 2. 간장은 끓여서 식힌다. 3. 항아리에 가죽잎을 담고 식힌 간장을 붓는다. 4. 2~3일 간격으로 3의 간장을 따라 내어 끓여 식힌 다음 다시 붓기를 3회 반복한다. 5. 먹을 때 양념으로 무친다.','가죽잎 500g,간장 3컵,소금 1/2컵','[양념] 고추장 3큰술, 물엿 1큰술, 깨소금 1작은술, 참기름 1작은술','고추장, 물엿에 담그는 장아찌도 있다.',null,'울산광역시농업기술센터, 울산향토음식, 2001 최수근·이연정·박성수, 향토음식 인지도에 관한 실증적 연구, 한국식생활문화학회지, 19(3), 2004','blank_image.png','가죽장아찌','부식류 > 장아찌류 > 장아찌류 > 간장에 담근 것',null,'가열하지 않는 음식 > 소금이나 장류에 절이는 음식 > 소금이나 장류에 절이는 음식');
Insert into FOOD.FOOD_TBL (ID,COOKING_INSTRUCTION,INGREDIENT,MINOR_INGREDIENT,REFERENCE,COOK,COOKING_ORIGIN,FOOD_IMG,FOOD_NAME,FOOD_TYPE,INFORMATION_PROVIDER,RECIPE) values (38,'1. 가죽은 끓는 물에 살짝 데쳐 꾸덕꾸덕하게 말린다. 2. 1의 말린 가죽과 고추장을 켜켜이 항아리에 담아 위를 눌러 3~4개월 숙성시킨다.','가죽 1kg,고추장 3컵',null,'·말린 가죽은 양념장(간장, 국간장, 물엿, 고추장, 고춧가루)에 무쳐 1개월 정도 숙성시키기도 한다. ·경상도에서는 참죽의 새순을 가죽이라고 한다.','김영자, 경상북도 고령군 덕곡면 반성 2리','경상북도 농촌진흥원, 우리의 맛 찾기 경북 향토음식, 1997 청도군 농업기술센터, 청도향토음식의 보고 석빙고, 2004 이연정, 경주 지역 향토음식의 성인의 연령별 이용실태 분석, 한국식생활문화학회지, 21(6), 2006','blank_image.png','가죽장아찌(참죽장아찌)','부식류 > 장아찌류 > 장아찌류 > 고추장에 담근 것',null,'가열하지 않는 음식 > 소금이나 장류에 절이는 음식 > 소금이나 장류에 절이는 음식');
Insert into FOOD.FOOD_TBL (ID,COOKING_INSTRUCTION,INGREDIENT,MINOR_INGREDIENT,REFERENCE,COOK,COOKING_ORIGIN,FOOD_IMG,FOOD_NAME,FOOD_TYPE,INFORMATION_PROVIDER,RECIPE) values (39,'1. 가죽은 깨끗이 씻어 놓는다. 2. 밀가루에 물과 소금을 넣어 조금 묽게 반죽한다. 3. 가죽잎에 밀가루 반죽을 묻힌 다음 식용유를 두른 팬에 지진다. 초간장을 곁들인다.','밀가루 220g(2컵), 물 400mL(2컵), 소금 1작은술, 식용유 적량 , 초간장 적량, 가죽잎 200g',null,null,null,'영동군농업기술센터, 영동군생활개선회 향토음식연구회, 감고을 영동의 우리 맛 발자취, 2003','e141c111-0ccd-4c1b-9829-63476ac8044d.jpg','가죽전(가죽잎부침개)','부식류 > 전류 > 전 > 채소류',null,'가열하여 익히는 음식 > 기름을 이용하여 익히는 음식 > 기름을 이용하여 익히는 음식');
Insert into FOOD.FOOD_TBL (ID,COOKING_INSTRUCTION,INGREDIENT,MINOR_INGREDIENT,REFERENCE,COOK,COOKING_ORIGIN,FOOD_IMG,FOOD_NAME,FOOD_TYPE,INFORMATION_PROVIDER,RECIPE) values (24,'1. 가자미는 비늘을 깨끗이 긁어 내고 아가미 밑으로 칼집을 넣어 내장을 빼낸 다음 깨끗이 씻어서 두 토막을 낸다. 2. 무는 납작하게 썬다(4×3×1cm). 3. 분량의 양념을 고루 섞어 담백한 조림장을 만든다. 4. 먼저 냄비 바닥에 무를 깔고 조림장을 조금 뿌린 다음 가자미를 얹고, 다시 남은 조림장을 골고루 뿌려 켜켜로 안친다. 물 3/4컵 정도를 냄비 가장자리에 돌려가며 붓는다. 5. 약한 불에서 서서히 조린다.','가자미 200g(2/3마리), 무 140g, 물 150mL(3/4컵)','[조림장] 간장 21g(1 1/4 큰술), 다진 파 7g(3/4큰술), 다진 마늘 6g(1작은술), 설탕 3g(1작은술), 고춧가루 3g(1/2큰술), 통깨 2g(2/3작은술)',null,null,'백승철, 별미 반찬·밑반찬, 서울문화사, 1999 농촌진흥청 농촌생활연구소(현 농촌자원개발연구소), 소비자가 알기 쉬운 식품영양가표, 2002','blank_image.png','가자미조림','부식류 > 조림류 > 조림 > 어패류',null,'가열하여 익히는 음식 > 물을 이용한 음식 > 약간의 수분을 양념과함께 넣고 익혀 양념이 식품에 스며들게 하는 음식');
Insert into FOOD.FOOD_TBL (ID,COOKING_INSTRUCTION,INGREDIENT,MINOR_INGREDIENT,REFERENCE,COOK,COOKING_ORIGIN,FOOD_IMG,FOOD_NAME,FOOD_TYPE,INFORMATION_PROVIDER,RECIPE) values (25,'1. 가자미는 씻어 물기를 빼고 2토막으로 자른다. 2. 냄비에 준비된 가자미를 넣고 조림장을 얹은 후 물을 부어 중불에서 조린다.','가자미(납세미) 700g(2마리), 물 200mL(1컵)','[조림장] 간장 2큰술, 고추장 1큰술, 다진마늘 1큰술, 물엿 1/2큰술','비린내가 없기 때문에 가자미로 미역국을 끓여서 먹기도 한다.','이미애, 경상남도 고성군 상리면 자은리　','울산광역시농업기술센터, 울산향토음식, 2001','blank_image.png','가자미조림(납세미조림)','부식류 > 조림류 > 조림 > 어패류',null,'가열하여 익히는 음식 > 물을 이용한 음식 > 약간의 수분을 양념과함께 넣고 익혀 양념이 식품에 스며들게 하는 음식');
Insert into FOOD.FOOD_TBL (ID,COOKING_INSTRUCTION,INGREDIENT,MINOR_INGREDIENT,REFERENCE,COOK,COOKING_ORIGIN,FOOD_IMG,FOOD_NAME,FOOD_TYPE,INFORMATION_PROVIDER,RECIPE) values (26,'1. 마른 고추는 1cm 간격으로 자른다. 2. 분량의 재료로 양념장을 만들어 끓여 식힌다. 3. 마른 가자미는 적당한 크기로 썬 다음 식용유에 바삭하게 튀겨 식힌다. 4. 양념장에 튀김 가자미를 넣고 골고루 버무리고 통깨를 뿌린다.','마른 가자미 200g, 통깨 약간','[양념장] 마른 고추 2개, 간장 4큰술, 고추장 1큰술, 고춧가루 2큰술, 물엿 1/2컵, 설탕 1/2큰술, 물 200mL(1컵), 다진 마늘 1작은술, 식용유 적량',null,'박미숙, 경상북도 경주시 내남면 이조리','포항시농업기술센터, 포항전통의 맛, 2004 경주시농업기술센터, 천년고도 경주 내림손맛, 2005','2723af2c-3bc2-4429-8bea-5a521db9fff3.jpg','가자미조림(미주구리조림)','부식류 > 조림류 > 조림 > 어패류','배금자, 경상북도 영덕군 영덕읍 남석2리 최태순, 경상북도 포항시 남구 대송면 송동리','가열하여 익히는 음식 > 물을 이용한 음식 > 약간의 수분을 양념과함께 넣고 익혀 양념이 식품에 스며들게 하는 음식');
Insert into FOOD.FOOD_TBL (ID,COOKING_INSTRUCTION,INGREDIENT,MINOR_INGREDIENT,REFERENCE,COOK,COOKING_ORIGIN,FOOD_IMG,FOOD_NAME,FOOD_TYPE,INFORMATION_PROVIDER,RECIPE) values (27,'1. 가죽은 깨끗이 씻어 물기를 뺀다. 2. 분량의 재료로 양념을 만들어 가죽에 양념을 넣고 가볍게 무친 후 깨소금을 뿌린다.','가죽 300g,깨소금 1/2큰술','[양념] 고추장 3큰술, 다진 파 1큰술, 다진 마늘 1큰술, 설탕 1작은술, 식초 1 1/2큰술, 참기름 1/2작은술','생채 또는 데쳐서 이용하기도 한다.','정계임, 경상남도 진주시 대안동',null,'57e422e6-cfb4-4e8a-88d5-aab32f63175e.jpg','가죽무침(나물)','부식류 > 나물류 > 생채 > 생채',null,'무치는 음식 > 생으로 무치는 음식 > 생으로 무치는 음식');
Insert into FOOD.FOOD_TBL (ID,COOKING_INSTRUCTION,INGREDIENT,MINOR_INGREDIENT,REFERENCE,COOK,COOKING_ORIGIN,FOOD_IMG,FOOD_NAME,FOOD_TYPE,INFORMATION_PROVIDER,RECIPE) values (28,'1. 이른 봄에 가죽잎을 따서 물에 소금을 약간 넣어 데쳐 말린다. 2. 찹쌀가루로 풀을 쒀 다진 마늘, 고춧가루, 통깨, 실고추를 넣고 간장으로 간한다. 3. 2의 풀을 살짝 말린 가죽에 발라 바짝 말린다. 4. 식용유에 튀겨 먹는다.','가죽잎 , 찹쌀가루 , 물 , 간장 , 다진 마늘 , 고춧가루 , 통깨 , 실고추 , 식용유 적량, 소금 약간',null,'참죽의 새순을 가죽이라고 한다.',null,'농촌진흥청, 향토음식, www2.rda.go.kr/food/, 2006','blank_image.png','가죽부각','부식류 > 마른찬류 > 부각 > 채소류',null,'가열하여 익히는 음식 > 기름을 이용하여 익히는 음식 > 기름을 이용하여 익히는 음식');
Insert into FOOD.FOOD_TBL (ID,COOKING_INSTRUCTION,INGREDIENT,MINOR_INGREDIENT,REFERENCE,COOK,COOKING_ORIGIN,FOOD_IMG,FOOD_NAME,FOOD_TYPE,INFORMATION_PROVIDER,RECIPE) values (29,'1. 어린 가죽잎은 끓는 물에 소금을 넣어 살짝 데친 후 꾸덕꾸덕하게 말린다. 2. 냄비에 밀가루, 물, 소금을 넣고 밀가루풀을 끓인다. 3. 말린 가죽잎에 밀가루풀을 발라 햇볕에 말린다. 4. 냄비에 찹쌀가루, 물, 소금을 넣고 찹쌀풀을 끓여 식힌 후 고춧가루, 통깨를 섞는다. 5. 3의 가죽잎에 고춧가루, 통깨를 섞은 찹쌀풀을 골고루 발라 햇볕에 바싹 말린다. 6. 겉면이 윤기나게 마르면 잘 보관해 두었다가 먹을 때 식용유에 튀긴다.','어린 가죽잎 400g, 고춧가루 3큰술, 통깨 2큰술, 소금 약간, 식용유 적량','<밀가루풀> 밀가루 55g(1/2컵), 소금 약간, 물 150mL(3/4컵) <찹쌀풀> 찹쌀가루 250g(2 1/2컵), 소금 1작은술, 물 750mL(3 3/4컵)','동백잎, 당귀잎, 들깻잎, 방아잎, 가죽, 아주까리잎, 뽕잎, 약초밀 등 여러 종류의 산야초를 부각으로 이용한다.','백영선, 경상남도 김해시','문화공보부 문화재관리국, 한국민속종합조사보고서(경상남도 편), 1972 경상남도 농촌진흥원, 경남향토음식, 1994 최수근·이연정·박성수, 향토음식 인지도에 관한 실증적 연구, 한국식생활문화학회지, 19(3), 2004 농촌진흥청, 향토음식, www2.rda.go.kr/food/, 2006','5c0fd8a5-a239-4fd6-b574-abfe745c4527.jpg','가죽부각(가죽자반)','부식류 > 마른찬류 > 부각 > 채소류','노광옥, 경상남도 밀양시 상남면 기산리 박순희, 경상남도 창원시 남양동','가열하여 익히는 음식 > 기름을 이용하여 익히는 음식 > 기름을 이용하여 익히는 음식');
Insert into FOOD.FOOD_TBL (ID,COOKING_INSTRUCTION,INGREDIENT,MINOR_INGREDIENT,REFERENCE,COOK,COOKING_ORIGIN,FOOD_IMG,FOOD_NAME,FOOD_TYPE,INFORMATION_PROVIDER,RECIPE) values (30,'1. 냄비에 물과 찹쌀가루를 넣고 끓인다. 2. 1에 들깻가루, 고춧가루, 고추장을 넣고 잘 섞은 후 국간장을 넣고 저으면서 걸쭉하게 끓인다. 3. 끓는 물에 소금을 넣고 가죽순을 살짝 데친 후 물기를 뺀다. 4. 2의 찹쌀풀에 가죽순을 넣어 골고루 두껍지 않게 무친 후 채반에 널어 바짝 말린다. 5. 먹을 때 가죽순을 170℃의 식용유에서 재빨리 튀겨 낸다.','가죽 1kg, 찹쌀가루 100g(1컵), 물 400mL(2컵), 국간장 1큰술, 들깻가루 1/2컵, 고춧가루 1큰술, 고추장 1큰술, 소금 약간, 식용유 적량',null,null,'박미숙, 경상북도 경주시 내남면 이조리','문화공보부 문화재관리국, 한국민속종합조사보고서(향토음식편), 1984 상주시농업기술센터, 상주 향토음식 맥잇기 고운 빛 깊은 맛, 2004 청도군농업기술센터, 청도향토음식의 보고 석빙고, 2004','05350c66-309f-4f9a-9413-78c47412579e.jpg','가죽부각(가죽자반튀김)','부식류 > 마른찬류 > 부각 > 채소류',null,'가열하여 익히는 음식 > 기름을 이용하여 익히는 음식 > 기름을 이용하여 익히는 음식');
--------------------------------------------------------
--  DDL for Index SYS_C007747
--------------------------------------------------------

  CREATE UNIQUE INDEX "FOOD"."SYS_C007747" ON "FOOD"."FOOD_TBL" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table FOOD_TBL
--------------------------------------------------------

  ALTER TABLE "FOOD"."FOOD_TBL" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "FOOD"."FOOD_TBL" MODIFY ("INGREDIENT" NOT NULL ENABLE);
  ALTER TABLE "FOOD"."FOOD_TBL" MODIFY ("FOOD_IMG" NOT NULL ENABLE);
  ALTER TABLE "FOOD"."FOOD_TBL" MODIFY ("FOOD_NAME" NOT NULL ENABLE);
  ALTER TABLE "FOOD"."FOOD_TBL" MODIFY ("FOOD_TYPE" NOT NULL ENABLE);
  ALTER TABLE "FOOD"."FOOD_TBL" MODIFY ("RECIPE" NOT NULL ENABLE);
  ALTER TABLE "FOOD"."FOOD_TBL" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
