CREATE TABLE "FOOD"."FOOD_TBL" ( 
	"ID" NUMBER(19,0), 
	"COOKING_INSTRUCTION" VARCHAR2(1000 CHAR), 
	"INGREDIENT" VARCHAR2(1000 CHAR), 
	"MINOR_INGREDIENT" VARCHAR2(1000 CHAR), 
	"REFERENCE" VARCHAR2(1000 CHAR), 
	"COOK" VARCHAR2(255 CHAR), 
	"COOKING_ORIGIN" VARCHAR2(255 CHAR), 
	"FOOD_IMG" VARCHAR2(255 CHAR), 
	"FOOD_NAME" VARCHAR2(255 CHAR), 
	"FOOD_TYPE" VARCHAR2(255 CHAR), 
	"INFORMATION_PROVIDER" VARCHAR2(255 CHAR), 
	"RECIPE" VARCHAR2(255 CHAR)
);

ALTER TABLE "FOOD"."FOOD_TBL" ADD PRIMARY KEY ("ID");
ALTER TABLE "FOOD"."FOOD_TBL" MODIFY ("RECIPE" NOT NULL ENABLE);
ALTER TABLE "FOOD"."FOOD_TBL" MODIFY ("FOOD_TYPE" NOT NULL ENABLE);
ALTER TABLE "FOOD"."FOOD_TBL" MODIFY ("FOOD_NAME" NOT NULL ENABLE);
ALTER TABLE "FOOD"."FOOD_TBL" MODIFY ("FOOD_IMG" NOT NULL ENABLE);
ALTER TABLE "FOOD"."FOOD_TBL" MODIFY ("INGREDIENT" NOT NULL ENABLE);
ALTER TABLE "FOOD"."FOOD_TBL" MODIFY ("ID" NOT NULL ENABLE);
  
CREATE SEQUENCE  "FOOD"."FOOD_SEQ"  
MINVALUE 1 
MAXVALUE 9999999999 
INCREMENT BY 1 
START WITH 1 
NOCYCLE;  